package com.ctfo.storage.dispatch.model;



import java.io.Serializable;


@SuppressWarnings("serial")
public class TrOperatorRole extends BaseModel implements Serializable{
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TR_OPERATOR_ROLE.AUTO_ID
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    private String autoId ;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TR_OPERATOR_ROLE.OP_ID
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    private String opId ;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TR_OPERATOR_ROLE.ROLE_ID
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    private String roleId ;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TR_OPERATOR_ROLE.AUTO_ID
     *
     * @return the value of TR_OPERATOR_ROLE.AUTO_ID
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public String getAutoId() {
        return autoId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TR_OPERATOR_ROLE.AUTO_ID
     *
     * @param autoId the value for TR_OPERATOR_ROLE.AUTO_ID
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public void setAutoId(String autoId) {
        this.autoId = autoId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TR_OPERATOR_ROLE.OP_ID
     *
     * @return the value of TR_OPERATOR_ROLE.OP_ID
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public String getOpId() {
        return opId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TR_OPERATOR_ROLE.OP_ID
     *
     * @param opId the value for TR_OPERATOR_ROLE.OP_ID
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public void setOpId(String opId) {
        this.opId = opId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TR_OPERATOR_ROLE.ROLE_ID
     *
     * @return the value of TR_OPERATOR_ROLE.ROLE_ID
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TR_OPERATOR_ROLE.ROLE_ID
     *
     * @param roleId the value for TR_OPERATOR_ROLE.ROLE_ID
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }
}