############################################################
## makefile of libunisql.a
############################################################
.SUFFIXES: .cpp

SOURCES  = qstring.cpp httpparser.cpp httpclient.cpp asynchttpclient.cpp httpresp.cpp httpserver.cpp
PROGRAM  = 
#CLIB     = libhttpagent.a 
SONAME	 = libhttpagent.so.2
LNNAME   = libhttpagent.so
LIBS     =

SPECIAL_LIBS = -lsocketex -lutils -llog -lthshare

include ${CTFOLIBS_HOME}/makefile.include

