package com.ctfo.sys.dao.impl;

import com.ctfo.local.daoImpl.GenericIbatisAbstract;
import com.ctfo.sys.beans.SysAlarmType;
import com.ctfo.sys.dao.SysAlarmTypeDAO;

public class SysAlarmTypeDAOImpl extends GenericIbatisAbstract<SysAlarmType, String>  implements SysAlarmTypeDAO {

  	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SYS_ALARM_TYPE
	 * @abatorgenerated  Mon Mar 24 16:46:46 CST 2014
	 */
	public void insert(SysAlarmType record) {
		getSqlMapClientTemplate().insert("SYS_ALARM_TYPE.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SYS_ALARM_TYPE
	 * @abatorgenerated  Mon Mar 24 16:46:46 CST 2014
	 */
	public int updateByPrimaryKey(SysAlarmType record) {
		int rows = getSqlMapClientTemplate().update("SYS_ALARM_TYPE.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SYS_ALARM_TYPE
	 * @abatorgenerated  Mon Mar 24 16:46:46 CST 2014
	 */
	public int updateByPrimaryKeySelective(SysAlarmType record) {
		int rows = getSqlMapClientTemplate().update("SYS_ALARM_TYPE.abatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SYS_ALARM_TYPE
	 * @abatorgenerated  Mon Mar 24 16:46:46 CST 2014
	 */
	public SysAlarmType selectByPrimaryKey(String alarmCode) {
		SysAlarmType key = new SysAlarmType();
		key.setAlarmCode(alarmCode);
		SysAlarmType record = (SysAlarmType) getSqlMapClientTemplate().queryForObject("SYS_ALARM_TYPE.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SYS_ALARM_TYPE
	 * @abatorgenerated  Mon Mar 24 16:46:46 CST 2014
	 */
	public int deleteByPrimaryKey(String alarmCode) {
		SysAlarmType key = new SysAlarmType();
		key.setAlarmCode(alarmCode);
		int rows = getSqlMapClientTemplate().delete("SYS_ALARM_TYPE.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}
}