package com.ctfo.sys.dao.impl;

import java.math.BigDecimal;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.ctfo.sys.beans.SysAlarmLevel;
import com.ctfo.sys.dao.SysAlarmLevelDAO;

public class SysAlarmLevelDAOImpl extends SqlMapClientDaoSupport implements SysAlarmLevelDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SYS_ALARM_LEVEL
	 * @abatorgenerated  Mon Mar 24 16:46:46 CST 2014
	 */
	public SysAlarmLevelDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SYS_ALARM_LEVEL
	 * @abatorgenerated  Mon Mar 24 16:46:46 CST 2014
	 */
	public void insert(SysAlarmLevel record) {
		getSqlMapClientTemplate().insert("SYS_ALARM_LEVEL.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SYS_ALARM_LEVEL
	 * @abatorgenerated  Mon Mar 24 16:46:46 CST 2014
	 */
	public int updateByPrimaryKey(SysAlarmLevel record) {
		int rows = getSqlMapClientTemplate().update("SYS_ALARM_LEVEL.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SYS_ALARM_LEVEL
	 * @abatorgenerated  Mon Mar 24 16:46:46 CST 2014
	 */
	public int updateByPrimaryKeySelective(SysAlarmLevel record) {
		int rows = getSqlMapClientTemplate().update("SYS_ALARM_LEVEL.abatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}


	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SYS_ALARM_LEVEL
	 * @abatorgenerated  Mon Mar 24 16:46:46 CST 2014
	 */
	public SysAlarmLevel selectByPrimaryKey(BigDecimal levelId) {
		SysAlarmLevel key = new SysAlarmLevel();
		key.setLevelId(levelId);
		SysAlarmLevel record = (SysAlarmLevel) getSqlMapClientTemplate().queryForObject("SYS_ALARM_LEVEL.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SYS_ALARM_LEVEL
	 * @abatorgenerated  Mon Mar 24 16:46:46 CST 2014
	 */
	public int deleteByPrimaryKey(BigDecimal levelId) {
		SysAlarmLevel key = new SysAlarmLevel();
		key.setLevelId(levelId);
		int rows = getSqlMapClientTemplate().delete("SYS_ALARM_LEVEL.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}
}