############################################################
## makefile of filesrv
############################################################
.SUFFIXES: .cpp

SOURCES  = main.cpp queuemgr.cpp
#SOURCES = testmain.cpp
PROGRAM  = qtester
CLIB     = 

SPECIAL_MACRO_FLAGS = -DRELEASE
SPECIAL_CCFLAGS   = 
SPECIAL_INCL_PATH = 
SPECIAL_LIB_PATH  = 

SPECIAL_LIBS = -lctfobase

include ${MTRANS_PRJ_HOME}/makefile.include