############################################################
## makefile of libunisql.a
############################################################
.SUFFIXES: .cpp

SOURCES  = cLog.cpp
PROGRAM  = 
#CLIB     = liblog.a 
LIBS     =
SONAME   = liblog.so.2
LNNAME   = liblog.so
#WAS_HOME = /home/tcsd/waservice

SPECIAL_LIBS = -lthshare

include ${CTFOLIBS_HOME}/makefile.include

