 ############################################################
## makefile of libunisql.a
############################################################
.SUFFIXES: .cpp

SOURCES  = publish.cpp
#SOURCES = testmain.cpp
PROGRAM  = 
CLIB     = libpublisher.a 
##SONAME   = libpublisher.so.1

SPECIAL_MACRO_FLAGS = -DRELEASE
SPECIAL_CCFLAGS   = 
SPECIAL_INCL_PATH = -I../../include -I../../share/node -I../include
SPECIAL_LIB_PATH  = 

#SPECIAL_LIBS = -lutils -llog -lthshare -lsocketex -lnetbaseex
SPECIAL_LIBS = -lctfobase

include ${MTRANS_PRJ_HOME}/makefile.include


