############################################################
## makefile of libsthread.a
############################################################
.SUFFIXES: .cpp

SOURCES  = Mutex.cpp Monitor.cpp Ref.cpp Util.cpp Thread.cpp

#cpppcap.cpp
PROGRAM  = 
#CLIB     = libthshare.a 
SONAME   = libthshare.so.2
LNNAME   = libthshare.so
LIBS     = 

include ${CTFOLIBS_HOME}/makefile.include

