package com.ctfo.combusiness.beans;

import java.math.BigDecimal;

public class TbCommFlux extends TbCommFluxKey {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_COMM_FLUX.ICCID_ELECTRON
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	private String iccidElectron;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_COMM_FLUX.DEVICE_NO
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	private String deviceNo;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_COMM_FLUX.COMM_CORP_CODE
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	private String commCorpCode;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_COMM_FLUX.FLUX_VALUE
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	private BigDecimal fluxValue;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_COMM_FLUX.CALL_TIME
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	private BigDecimal callTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_COMM_FLUX.CLOSE_TIME
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	private BigDecimal closeTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_COMM_FLUX.CREATE_BY
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	private BigDecimal createBy;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_COMM_FLUX.CREATE_TIME
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	private BigDecimal createTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_COMM_FLUX.UPDATE_BY
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	private BigDecimal updateBy;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_COMM_FLUX.UPDATE_TIME
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	private BigDecimal updateTime;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_COMM_FLUX.ICCID_ELECTRON
	 * @return  the value of TB_COMM_FLUX.ICCID_ELECTRON
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public String getIccidElectron() {
		return iccidElectron;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_COMM_FLUX.ICCID_ELECTRON
	 * @param iccidElectron  the value for TB_COMM_FLUX.ICCID_ELECTRON
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public void setIccidElectron(String iccidElectron) {
		this.iccidElectron = iccidElectron;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_COMM_FLUX.DEVICE_NO
	 * @return  the value of TB_COMM_FLUX.DEVICE_NO
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public String getDeviceNo() {
		return deviceNo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_COMM_FLUX.DEVICE_NO
	 * @param deviceNo  the value for TB_COMM_FLUX.DEVICE_NO
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public void setDeviceNo(String deviceNo) {
		this.deviceNo = deviceNo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_COMM_FLUX.COMM_CORP_CODE
	 * @return  the value of TB_COMM_FLUX.COMM_CORP_CODE
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public String getCommCorpCode() {
		return commCorpCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_COMM_FLUX.COMM_CORP_CODE
	 * @param commCorpCode  the value for TB_COMM_FLUX.COMM_CORP_CODE
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public void setCommCorpCode(String commCorpCode) {
		this.commCorpCode = commCorpCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_COMM_FLUX.FLUX_VALUE
	 * @return  the value of TB_COMM_FLUX.FLUX_VALUE
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public BigDecimal getFluxValue() {
		return fluxValue;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_COMM_FLUX.FLUX_VALUE
	 * @param fluxValue  the value for TB_COMM_FLUX.FLUX_VALUE
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public void setFluxValue(BigDecimal fluxValue) {
		this.fluxValue = fluxValue;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_COMM_FLUX.CALL_TIME
	 * @return  the value of TB_COMM_FLUX.CALL_TIME
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public BigDecimal getCallTime() {
		return callTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_COMM_FLUX.CALL_TIME
	 * @param callTime  the value for TB_COMM_FLUX.CALL_TIME
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public void setCallTime(BigDecimal callTime) {
		this.callTime = callTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_COMM_FLUX.CLOSE_TIME
	 * @return  the value of TB_COMM_FLUX.CLOSE_TIME
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public BigDecimal getCloseTime() {
		return closeTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_COMM_FLUX.CLOSE_TIME
	 * @param closeTime  the value for TB_COMM_FLUX.CLOSE_TIME
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public void setCloseTime(BigDecimal closeTime) {
		this.closeTime = closeTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_COMM_FLUX.CREATE_BY
	 * @return  the value of TB_COMM_FLUX.CREATE_BY
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public BigDecimal getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_COMM_FLUX.CREATE_BY
	 * @param createBy  the value for TB_COMM_FLUX.CREATE_BY
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public void setCreateBy(BigDecimal createBy) {
		this.createBy = createBy;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_COMM_FLUX.CREATE_TIME
	 * @return  the value of TB_COMM_FLUX.CREATE_TIME
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public BigDecimal getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_COMM_FLUX.CREATE_TIME
	 * @param createTime  the value for TB_COMM_FLUX.CREATE_TIME
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public void setCreateTime(BigDecimal createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_COMM_FLUX.UPDATE_BY
	 * @return  the value of TB_COMM_FLUX.UPDATE_BY
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public BigDecimal getUpdateBy() {
		return updateBy;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_COMM_FLUX.UPDATE_BY
	 * @param updateBy  the value for TB_COMM_FLUX.UPDATE_BY
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public void setUpdateBy(BigDecimal updateBy) {
		this.updateBy = updateBy;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_COMM_FLUX.UPDATE_TIME
	 * @return  the value of TB_COMM_FLUX.UPDATE_TIME
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public BigDecimal getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_COMM_FLUX.UPDATE_TIME
	 * @param updateTime  the value for TB_COMM_FLUX.UPDATE_TIME
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public void setUpdateTime(BigDecimal updateTime) {
		this.updateTime = updateTime;
	}
}