package com.ctfo.combusiness.beans;

import java.math.BigDecimal;

public class TbCommFluxKey {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_COMM_FLUX.SID
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	private BigDecimal sid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_COMM_FLUX.STAT_DATE
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	private BigDecimal statDate;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_COMM_FLUX.SID
	 * @return  the value of TB_COMM_FLUX.SID
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public BigDecimal getSid() {
		return sid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_COMM_FLUX.SID
	 * @param sid  the value for TB_COMM_FLUX.SID
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public void setSid(BigDecimal sid) {
		this.sid = sid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_COMM_FLUX.STAT_DATE
	 * @return  the value of TB_COMM_FLUX.STAT_DATE
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public BigDecimal getStatDate() {
		return statDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_COMM_FLUX.STAT_DATE
	 * @param statDate  the value for TB_COMM_FLUX.STAT_DATE
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public void setStatDate(BigDecimal statDate) {
		this.statDate = statDate;
	}
}