package com.ctfo.combusiness.beans;

import com.ctfo.local.bean.ETB_Base;

@SuppressWarnings("serial")
public class TbFeedback extends ETB_Base {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TB_FEEDBACK.REPLY_ID
     *
     * @abatorgenerated Wed Oct 12 15:30:14 CST 2011
     */
    private Long replyId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TB_FEEDBACK.REPLY_TYPE
     *
     * @abatorgenerated Wed Oct 12 15:30:14 CST 2011
     */
    private String replyType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TB_FEEDBACK.REPLY_THEME
     *
     * @abatorgenerated Wed Oct 12 15:30:14 CST 2011
     */
    private String replyTheme;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TB_FEEDBACK.PUBLISH_STATUS
     *
     * @abatorgenerated Wed Oct 12 15:30:14 CST 2011
     */
    private String publishStatus;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TB_FEEDBACK.PUBLISH_TIME
     *
     * @abatorgenerated Wed Oct 12 15:30:14 CST 2011
     */
    private Long publishTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TB_FEEDBACK.REPLY_FLAG
     *
     * @abatorgenerated Wed Oct 12 15:30:14 CST 2011
     */
    private String replyFlag;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TB_FEEDBACK.PARENT_REPLY_ID
     *
     * @abatorgenerated Wed Oct 12 15:30:14 CST 2011
     */
    private Long parentReplyId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TB_FEEDBACK.ENT_ID
     *
     * @abatorgenerated Wed Oct 12 15:30:14 CST 2011
     */
    private Long entId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TB_FEEDBACK.CREATE_BY
     *
     * @abatorgenerated Wed Oct 12 15:30:14 CST 2011
     */
    private Long createBy;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TB_FEEDBACK.CREATE_TIME
     *
     * @abatorgenerated Wed Oct 12 15:30:14 CST 2011
     */
    private Long createTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TB_FEEDBACK.UPDATE_BY
     *
     * @abatorgenerated Wed Oct 12 15:30:14 CST 2011
     */
    private Long updateBy;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TB_FEEDBACK.UPDATE_TIME
     *
     * @abatorgenerated Wed Oct 12 15:30:14 CST 2011
     */
    private Long updateTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TB_FEEDBACK.ENABLE_FLAG
     *
     * @abatorgenerated Wed Oct 12 15:30:14 CST 2011
     */
    private String enableFlag;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TB_FEEDBACK.REPLY_CONTENT
     *
     * @abatorgenerated Wed Oct 12 15:30:14 CST 2011
     */
    private String replyContent;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TB_FEEDBACK.REPLY_ID
     *
     * @return the value of TB_FEEDBACK.REPLY_ID
     *
     * @abatorgenerated Wed Oct 12 15:30:14 CST 2011
     */
    public Long getReplyId() {
        return replyId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TB_FEEDBACK.REPLY_ID
     *
     * @param replyId the value for TB_FEEDBACK.REPLY_ID
     *
     * @abatorgenerated Wed Oct 12 15:30:14 CST 2011
     */
    public void setReplyId(Long replyId) {
        this.replyId = replyId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TB_FEEDBACK.REPLY_TYPE
     *
     * @return the value of TB_FEEDBACK.REPLY_TYPE
     *
     * @abatorgenerated Wed Oct 12 15:30:14 CST 2011
     */
    public String getReplyType() {
        return replyType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TB_FEEDBACK.REPLY_TYPE
     *
     * @param replyType the value for TB_FEEDBACK.REPLY_TYPE
     *
     * @abatorgenerated Wed Oct 12 15:30:14 CST 2011
     */
    public void setReplyType(String replyType) {
        this.replyType = replyType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TB_FEEDBACK.REPLY_THEME
     *
     * @return the value of TB_FEEDBACK.REPLY_THEME
     *
     * @abatorgenerated Wed Oct 12 15:30:14 CST 2011
     */
    public String getReplyTheme() {
        return replyTheme;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TB_FEEDBACK.REPLY_THEME
     *
     * @param replyTheme the value for TB_FEEDBACK.REPLY_THEME
     *
     * @abatorgenerated Wed Oct 12 15:30:14 CST 2011
     */
    public void setReplyTheme(String replyTheme) {
        this.replyTheme = replyTheme;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TB_FEEDBACK.PUBLISH_STATUS
     *
     * @return the value of TB_FEEDBACK.PUBLISH_STATUS
     *
     * @abatorgenerated Wed Oct 12 15:30:14 CST 2011
     */
    public String getPublishStatus() {
        return publishStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TB_FEEDBACK.PUBLISH_STATUS
     *
     * @param publishStatus the value for TB_FEEDBACK.PUBLISH_STATUS
     *
     * @abatorgenerated Wed Oct 12 15:30:14 CST 2011
     */
    public void setPublishStatus(String publishStatus) {
        this.publishStatus = publishStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TB_FEEDBACK.PUBLISH_TIME
     *
     * @return the value of TB_FEEDBACK.PUBLISH_TIME
     *
     * @abatorgenerated Wed Oct 12 15:30:14 CST 2011
     */
    public Long getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TB_FEEDBACK.PUBLISH_TIME
     *
     * @param publishTime the value for TB_FEEDBACK.PUBLISH_TIME
     *
     * @abatorgenerated Wed Oct 12 15:30:14 CST 2011
     */
    public void setPublishTime(Long publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TB_FEEDBACK.REPLY_FLAG
     *
     * @return the value of TB_FEEDBACK.REPLY_FLAG
     *
     * @abatorgenerated Wed Oct 12 15:30:14 CST 2011
     */
    public String getReplyFlag() {
        return replyFlag;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TB_FEEDBACK.REPLY_FLAG
     *
     * @param replyFlag the value for TB_FEEDBACK.REPLY_FLAG
     *
     * @abatorgenerated Wed Oct 12 15:30:14 CST 2011
     */
    public void setReplyFlag(String replyFlag) {
        this.replyFlag = replyFlag;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TB_FEEDBACK.PARENT_REPLY_ID
     *
     * @return the value of TB_FEEDBACK.PARENT_REPLY_ID
     *
     * @abatorgenerated Wed Oct 12 15:30:14 CST 2011
     */
    public Long getParentReplyId() {
        return parentReplyId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TB_FEEDBACK.PARENT_REPLY_ID
     *
     * @param parentReplyId the value for TB_FEEDBACK.PARENT_REPLY_ID
     *
     * @abatorgenerated Wed Oct 12 15:30:14 CST 2011
     */
    public void setParentReplyId(Long parentReplyId) {
        this.parentReplyId = parentReplyId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TB_FEEDBACK.ENT_ID
     *
     * @return the value of TB_FEEDBACK.ENT_ID
     *
     * @abatorgenerated Wed Oct 12 15:30:14 CST 2011
     */
    public Long getEntId() {
        return entId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TB_FEEDBACK.ENT_ID
     *
     * @param entId the value for TB_FEEDBACK.ENT_ID
     *
     * @abatorgenerated Wed Oct 12 15:30:14 CST 2011
     */
    public void setEntId(Long entId) {
        this.entId = entId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TB_FEEDBACK.CREATE_BY
     *
     * @return the value of TB_FEEDBACK.CREATE_BY
     *
     * @abatorgenerated Wed Oct 12 15:30:14 CST 2011
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TB_FEEDBACK.CREATE_BY
     *
     * @param createBy the value for TB_FEEDBACK.CREATE_BY
     *
     * @abatorgenerated Wed Oct 12 15:30:14 CST 2011
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TB_FEEDBACK.CREATE_TIME
     *
     * @return the value of TB_FEEDBACK.CREATE_TIME
     *
     * @abatorgenerated Wed Oct 12 15:30:14 CST 2011
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TB_FEEDBACK.CREATE_TIME
     *
     * @param createTime the value for TB_FEEDBACK.CREATE_TIME
     *
     * @abatorgenerated Wed Oct 12 15:30:14 CST 2011
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TB_FEEDBACK.UPDATE_BY
     *
     * @return the value of TB_FEEDBACK.UPDATE_BY
     *
     * @abatorgenerated Wed Oct 12 15:30:14 CST 2011
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TB_FEEDBACK.UPDATE_BY
     *
     * @param updateBy the value for TB_FEEDBACK.UPDATE_BY
     *
     * @abatorgenerated Wed Oct 12 15:30:14 CST 2011
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TB_FEEDBACK.UPDATE_TIME
     *
     * @return the value of TB_FEEDBACK.UPDATE_TIME
     *
     * @abatorgenerated Wed Oct 12 15:30:14 CST 2011
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TB_FEEDBACK.UPDATE_TIME
     *
     * @param updateTime the value for TB_FEEDBACK.UPDATE_TIME
     *
     * @abatorgenerated Wed Oct 12 15:30:14 CST 2011
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TB_FEEDBACK.ENABLE_FLAG
     *
     * @return the value of TB_FEEDBACK.ENABLE_FLAG
     *
     * @abatorgenerated Wed Oct 12 15:30:14 CST 2011
     */
    public String getEnableFlag() {
        return enableFlag;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TB_FEEDBACK.ENABLE_FLAG
     *
     * @param enableFlag the value for TB_FEEDBACK.ENABLE_FLAG
     *
     * @abatorgenerated Wed Oct 12 15:30:14 CST 2011
     */
    public void setEnableFlag(String enableFlag) {
        this.enableFlag = enableFlag;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TB_FEEDBACK.REPLY_CONTENT
     *
     * @return the value of TB_FEEDBACK.REPLY_CONTENT
     *
     * @abatorgenerated Wed Oct 12 15:30:14 CST 2011
     */
    public String getReplyContent() {
        return replyContent;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TB_FEEDBACK.REPLY_CONTENT
     *
     * @param replyContent the value for TB_FEEDBACK.REPLY_CONTENT
     *
     * @abatorgenerated Wed Oct 12 15:30:14 CST 2011
     */
    public void setReplyContent(String replyContent) {
        this.replyContent = replyContent;
    }
}