package com.ctfo.combusiness.beans;

public class TbInfoAttach {
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_INFO_ATTACH.ATTACH_ID
	 * /BaseInfoSer/beans_src/com/ctfo/combusiness/beans/@abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	private String attachId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_INFO_ATTACH.ATTACH_TYPE
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	private String attachType;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_INFO_ATTACH.INFO_ID
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	private String infoId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_INFO_ATTACH.ATTACH_THEME
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	private String attachTheme;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_INFO_ATTACH.ATTACH_URI
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	private String attachUri;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_INFO_ATTACH.ATTACH_ID
	 * @return  the value of TB_INFO_ATTACH.ATTACH_ID
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public String getAttachId() {
		return attachId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_INFO_ATTACH.ATTACH_ID
	 * @param attachId  the value for TB_INFO_ATTACH.ATTACH_ID
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public void setAttachId(String attachId) {
		this.attachId = attachId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_INFO_ATTACH.ATTACH_TYPE
	 * @return  the value of TB_INFO_ATTACH.ATTACH_TYPE
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public String getAttachType() {
		return attachType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_INFO_ATTACH.ATTACH_TYPE
	 * @param attachType  the value for TB_INFO_ATTACH.ATTACH_TYPE
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public void setAttachType(String attachType) {
		this.attachType = attachType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_INFO_ATTACH.INFO_ID
	 * @return  the value of TB_INFO_ATTACH.INFO_ID
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public String getInfoId() {
		return infoId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_INFO_ATTACH.INFO_ID
	 * @param infoId  the value for TB_INFO_ATTACH.INFO_ID
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public void setInfoId(String infoId) {
		this.infoId = infoId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_INFO_ATTACH.ATTACH_THEME
	 * @return  the value of TB_INFO_ATTACH.ATTACH_THEME
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public String getAttachTheme() {
		return attachTheme;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_INFO_ATTACH.ATTACH_THEME
	 * @param attachTheme  the value for TB_INFO_ATTACH.ATTACH_THEME
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public void setAttachTheme(String attachTheme) {
		this.attachTheme = attachTheme;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_INFO_ATTACH.ATTACH_URI
	 * @return  the value of TB_INFO_ATTACH.ATTACH_URI
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public String getAttachUri() {
		return attachUri;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_INFO_ATTACH.ATTACH_URI
	 * @param attachUri  the value for TB_INFO_ATTACH.ATTACH_URI
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public void setAttachUri(String attachUri) {
		this.attachUri = attachUri;
	}
}