package com.ctfo.combusiness.beans;

import java.math.BigDecimal;

public class TbServicesPoi {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_SERVICES_POI.POI_ID
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	private String poiId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_SERVICES_POI.POI_NAME
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	private String poiName;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_SERVICES_POI.POI_LAT
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	private BigDecimal poiLat;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_SERVICES_POI.POI_LON
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	private BigDecimal poiLon;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_SERVICES_POI.POI_CODE
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	private String poiCode;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_SERVICES_POI.POI_TYPE
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	private String poiType;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_SERVICES_POI.POI_LEVEL
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	private String poiLevel;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_SERVICES_POI.POI_SERVICETYPE
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	private String poiServicetype;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_SERVICES_POI.COUNTRY_ID
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	private String countryId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_SERVICES_POI.PROVINCE_ID
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	private String provinceId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_SERVICES_POI.CITY_ID
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	private String cityId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_SERVICES_POI.CONCATE_TEL
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	private String concateTel;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_SERVICES_POI.CONCATE_FAX
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	private String concateFax;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_SERVICES_POI.POI_ADDRESS
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	private String poiAddress;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_SERVICES_POI.CONCATE_POS
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	private String concatePos;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_SERVICES_POI.EMAIL
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	private String email;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_SERVICES_POI.WEBSITE
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	private String website;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_SERVICES_POI.CONCATE_PERSON
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	private String concatePerson;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_SERVICES_POI.REMARK
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	private String remark;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_SERVICES_POI.CREATE_BY
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	private String createBy;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_SERVICES_POI.CREATE_TIME
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	private Long createTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_SERVICES_POI.UPDATE_BY
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	private String updateBy;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_SERVICES_POI.UPDATE_TIME
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	private Long updateTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_SERVICES_POI.ENABLE_FLAG
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	private String enableFlag;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_SERVICES_POI.POI_ID
	 * @return  the value of TB_SERVICES_POI.POI_ID
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public String getPoiId() {
		return poiId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_SERVICES_POI.POI_ID
	 * @param poiId  the value for TB_SERVICES_POI.POI_ID
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public void setPoiId(String poiId) {
		this.poiId = poiId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_SERVICES_POI.POI_NAME
	 * @return  the value of TB_SERVICES_POI.POI_NAME
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public String getPoiName() {
		return poiName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_SERVICES_POI.POI_NAME
	 * @param poiName  the value for TB_SERVICES_POI.POI_NAME
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public void setPoiName(String poiName) {
		this.poiName = poiName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_SERVICES_POI.POI_LAT
	 * @return  the value of TB_SERVICES_POI.POI_LAT
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public BigDecimal getPoiLat() {
		return poiLat;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_SERVICES_POI.POI_LAT
	 * @param poiLat  the value for TB_SERVICES_POI.POI_LAT
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public void setPoiLat(BigDecimal poiLat) {
		this.poiLat = poiLat;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_SERVICES_POI.POI_LON
	 * @return  the value of TB_SERVICES_POI.POI_LON
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public BigDecimal getPoiLon() {
		return poiLon;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_SERVICES_POI.POI_LON
	 * @param poiLon  the value for TB_SERVICES_POI.POI_LON
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public void setPoiLon(BigDecimal poiLon) {
		this.poiLon = poiLon;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_SERVICES_POI.POI_CODE
	 * @return  the value of TB_SERVICES_POI.POI_CODE
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public String getPoiCode() {
		return poiCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_SERVICES_POI.POI_CODE
	 * @param poiCode  the value for TB_SERVICES_POI.POI_CODE
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public void setPoiCode(String poiCode) {
		this.poiCode = poiCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_SERVICES_POI.POI_TYPE
	 * @return  the value of TB_SERVICES_POI.POI_TYPE
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public String getPoiType() {
		return poiType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_SERVICES_POI.POI_TYPE
	 * @param poiType  the value for TB_SERVICES_POI.POI_TYPE
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public void setPoiType(String poiType) {
		this.poiType = poiType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_SERVICES_POI.POI_LEVEL
	 * @return  the value of TB_SERVICES_POI.POI_LEVEL
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public String getPoiLevel() {
		return poiLevel;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_SERVICES_POI.POI_LEVEL
	 * @param poiLevel  the value for TB_SERVICES_POI.POI_LEVEL
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public void setPoiLevel(String poiLevel) {
		this.poiLevel = poiLevel;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_SERVICES_POI.POI_SERVICETYPE
	 * @return  the value of TB_SERVICES_POI.POI_SERVICETYPE
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public String getPoiServicetype() {
		return poiServicetype;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_SERVICES_POI.POI_SERVICETYPE
	 * @param poiServicetype  the value for TB_SERVICES_POI.POI_SERVICETYPE
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public void setPoiServicetype(String poiServicetype) {
		this.poiServicetype = poiServicetype;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_SERVICES_POI.COUNTRY_ID
	 * @return  the value of TB_SERVICES_POI.COUNTRY_ID
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public String getCountryId() {
		return countryId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_SERVICES_POI.COUNTRY_ID
	 * @param countryId  the value for TB_SERVICES_POI.COUNTRY_ID
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public void setCountryId(String countryId) {
		this.countryId = countryId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_SERVICES_POI.PROVINCE_ID
	 * @return  the value of TB_SERVICES_POI.PROVINCE_ID
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public String getProvinceId() {
		return provinceId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_SERVICES_POI.PROVINCE_ID
	 * @param provinceId  the value for TB_SERVICES_POI.PROVINCE_ID
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public void setProvinceId(String provinceId) {
		this.provinceId = provinceId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_SERVICES_POI.CITY_ID
	 * @return  the value of TB_SERVICES_POI.CITY_ID
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public String getCityId() {
		return cityId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_SERVICES_POI.CITY_ID
	 * @param cityId  the value for TB_SERVICES_POI.CITY_ID
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public void setCityId(String cityId) {
		this.cityId = cityId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_SERVICES_POI.CONCATE_TEL
	 * @return  the value of TB_SERVICES_POI.CONCATE_TEL
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public String getConcateTel() {
		return concateTel;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_SERVICES_POI.CONCATE_TEL
	 * @param concateTel  the value for TB_SERVICES_POI.CONCATE_TEL
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public void setConcateTel(String concateTel) {
		this.concateTel = concateTel;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_SERVICES_POI.CONCATE_FAX
	 * @return  the value of TB_SERVICES_POI.CONCATE_FAX
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public String getConcateFax() {
		return concateFax;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_SERVICES_POI.CONCATE_FAX
	 * @param concateFax  the value for TB_SERVICES_POI.CONCATE_FAX
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public void setConcateFax(String concateFax) {
		this.concateFax = concateFax;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_SERVICES_POI.POI_ADDRESS
	 * @return  the value of TB_SERVICES_POI.POI_ADDRESS
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public String getPoiAddress() {
		return poiAddress;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_SERVICES_POI.POI_ADDRESS
	 * @param poiAddress  the value for TB_SERVICES_POI.POI_ADDRESS
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public void setPoiAddress(String poiAddress) {
		this.poiAddress = poiAddress;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_SERVICES_POI.CONCATE_POS
	 * @return  the value of TB_SERVICES_POI.CONCATE_POS
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public String getConcatePos() {
		return concatePos;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_SERVICES_POI.CONCATE_POS
	 * @param concatePos  the value for TB_SERVICES_POI.CONCATE_POS
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public void setConcatePos(String concatePos) {
		this.concatePos = concatePos;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_SERVICES_POI.EMAIL
	 * @return  the value of TB_SERVICES_POI.EMAIL
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_SERVICES_POI.EMAIL
	 * @param email  the value for TB_SERVICES_POI.EMAIL
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_SERVICES_POI.WEBSITE
	 * @return  the value of TB_SERVICES_POI.WEBSITE
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public String getWebsite() {
		return website;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_SERVICES_POI.WEBSITE
	 * @param website  the value for TB_SERVICES_POI.WEBSITE
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public void setWebsite(String website) {
		this.website = website;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_SERVICES_POI.CONCATE_PERSON
	 * @return  the value of TB_SERVICES_POI.CONCATE_PERSON
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public String getConcatePerson() {
		return concatePerson;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_SERVICES_POI.CONCATE_PERSON
	 * @param concatePerson  the value for TB_SERVICES_POI.CONCATE_PERSON
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public void setConcatePerson(String concatePerson) {
		this.concatePerson = concatePerson;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_SERVICES_POI.REMARK
	 * @return  the value of TB_SERVICES_POI.REMARK
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_SERVICES_POI.REMARK
	 * @param remark  the value for TB_SERVICES_POI.REMARK
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_SERVICES_POI.CREATE_BY
	 * @return  the value of TB_SERVICES_POI.CREATE_BY
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public String getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_SERVICES_POI.CREATE_BY
	 * @param createBy  the value for TB_SERVICES_POI.CREATE_BY
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_SERVICES_POI.CREATE_TIME
	 * @return  the value of TB_SERVICES_POI.CREATE_TIME
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public Long getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_SERVICES_POI.CREATE_TIME
	 * @param createTime  the value for TB_SERVICES_POI.CREATE_TIME
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public void setCreateTime(Long createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_SERVICES_POI.UPDATE_BY
	 * @return  the value of TB_SERVICES_POI.UPDATE_BY
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public String getUpdateBy() {
		return updateBy;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_SERVICES_POI.UPDATE_BY
	 * @param updateBy  the value for TB_SERVICES_POI.UPDATE_BY
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_SERVICES_POI.UPDATE_TIME
	 * @return  the value of TB_SERVICES_POI.UPDATE_TIME
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public Long getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_SERVICES_POI.UPDATE_TIME
	 * @param updateTime  the value for TB_SERVICES_POI.UPDATE_TIME
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public void setUpdateTime(Long updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_SERVICES_POI.ENABLE_FLAG
	 * @return  the value of TB_SERVICES_POI.ENABLE_FLAG
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public String getEnableFlag() {
		return enableFlag;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_SERVICES_POI.ENABLE_FLAG
	 * @param enableFlag  the value for TB_SERVICES_POI.ENABLE_FLAG
	 * @abatorgenerated  Sat Sep 24 18:01:14 CST 2011
	 */
	public void setEnableFlag(String enableFlag) {
		this.enableFlag = enableFlag;
	}
}