############################################################
## makefile of libtinyxml.a
############################################################
.SUFFIXES: .cpp

SOURCES  = tinystr.cpp tinyxml.cpp tinyxmlerror.cpp tinyxmlparser.cpp

#cpppcap.cpp
PROGRAM  = 
#CLIB     = libtinyxml.a 
SONAME   = libtinyxml.so.2
LNNAME	 = libtinyxml.so
LIBS     = 

include ${CTFOLIBS_HOME}/makefile.include

