package com.ctfo.sys.dao;

import com.ctfo.sys.beans.SysSpPosition;

public interface SysSpPositionDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SYS_SP_POSITION
	 * @abatorgenerated  Mon Mar 24 16:46:48 CST 2014
	 */
	void insert(SysSpPosition record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SYS_SP_POSITION
	 * @abatorgenerated  Mon Mar 24 16:46:48 CST 2014
	 */
	int updateByPrimaryKey(SysSpPosition record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SYS_SP_POSITION
	 * @abatorgenerated  Mon Mar 24 16:46:48 CST 2014
	 */
	int updateByPrimaryKeySelective(SysSpPosition record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SYS_SP_POSITION
	 * @abatorgenerated  Mon Mar 24 16:46:48 CST 2014
	 */
	SysSpPosition selectByPrimaryKey(String positionCode);
}