var menuList = {
	"l": 0,
	"c": [{
		"name": "首页",
		"icon": "nav_1",
		"auth": "FG_MEMU_HOMEPAGE",
		"url": "model/home/home.html",
		"mid": "homePage",
		"l": 1,
		"isHomePage": true
	}, {
		"name": "业务管理",
		"icon": "nav_11",
		"auth": "FG_MEMU_BUSINESS",
		"url": "",
		"mid": "",
		"l": 1,
		"c": [{
			"name": "注册鉴权",
			"icon": "ico189",
			"auth": "FG_MEMU_BUSINESS_AUTHMANAGE",
			"url": "model/operations/authManage.html",
			"mid": "authManage",
			"l": 2
		}, {
			"name": "云备份管理",
			"icon": "ico196",
			"auth": "FG_MEMU_BUSINESS_CLOUDMANAGE",
			"url": "model/operations/cloudManage.html",
			"mid": "cloudManage",
			"l": 2
		}]
	}, {
		"name": "数据分析",
		"icon": "nav_12",
		"auth": "FG_MEMU_DATAANALSIS",
		"url": "",
		"mid": "",
		"l": 1,
		"c": [{
			"name": "维修单统计",
			"icon": "ico189",
			"auth": "FG_MEMU_DATAANALSIS_REPAIRSTAT",
			"url": "model/operations/repairStat.html",
			"mid": "repairStat",
			"l": 2
		}]
	}, {
		"name": "系统监控",
		"icon": "nav_13",
		"auth": "FG_MEMU_SYSMONITOR",
		"url": "",
		"mid": "",
		"l": 1,
		"c": [{
			"name": "服务端状态",
			"icon": "ico189",
			"auth": "FG_MEMU_SYSMONITOR_ONLINESTATUSMANAGE",
			"url": "model/operations/onlineStatusManage.html",
			"mid": "onlineStatusManage",
			"l": 2
		}, {
			"name": "链路管理",
			"icon": "ico196",
			"auth": "FG_MEMU_SYSMONITOR_LINKMANAGE",
			"url": "model/operations/linkManage.html",
			"mid": "linkManage",
			"l": 2
		}, {
			"name": "在线用户",
			"icon": "ico193",
			"auth": "FG_MEMU_SYSMONITOR_ONLINEUSERSMANAGE",
			"url": "model/operations/onlineUsersManage.html",
			"mid": "onlineUsersManage",
			"l": 2
		}, {
			"name": "用户行为监控",
			"icon": "ico194",
			"auth": "FG_MEMU_SYSMONITOR_USERBEHAVIORMANAGE",
			"url": "model/operations/userBehaviorManage.html",
			"mid": "userBehaviorManage",
			"l": 2
		}, {
			"name": "访问统计",
			"icon": "ico194",
			"auth": "FG_MEMU_SYSMONITOR_VISITSTAT",
			"url": "model/operations/visitStat.html",
			"mid": "visitStat",
			"l": 2
		}]
	}, {
		"name": "数据管理",
		"icon": "nav_14",
		"auth": "FG_MEMU_DATAMANAGE",
		"url": "",
		"mid": "",
		"l": 1,
		"c": [{
			"name": "用户档案",
			"icon": "ico189",
			"auth": "FG_MEMU_DATAMANAGER_ARCHIVESMANAGE",
			"url": "model/operations/archivesManage.html",
			"mid": "archivesManage",
			"l": 2
		}, {
			"name": "用户档案列表",
			"icon": "ico189",
			"auth": "FG_MEMU_DATAMANAGER_USERFILELISTMANAGE",
			"url": "model/operations/userFileListManage.html",
			"mid": "userFileListManage",
			"isHidden":"1",
			"l": 2
		}]
	}, {
		"name": "系统维护",
		"icon": "nav_15",
		"auth": "FG_MEMU_SYSTEM",
		"url": "",
		"mid": "",
		"l": 1,
		"c": [{
			"name": "公司管理",
			"icon": "ico189",
			"auth": "FG_MEMU_SYSTEM_COMPANYMANAGE",
			"url": "model/operations/companyManage.html",
			"mid": "companyManage",
			"l": 2
		}, {
			"name": "组织管理",
			"icon": "ico193",
			"auth": "FG_MEMU_SYSTEM_VEHICLETEAMMANAGE",
			"url": "model/operations/vehicleTeamManage.html",
			"mid": "vehicleTeamManage",
			"l": 2
		}, {
			"name": "角色管理",
			"icon": "ico194",
			"auth": "FG_MEMU_SYSTEM_ROLEMANAGE",
			"url": "model/operations/roleManage.html",
			"mid": "roleManage",
			"l": 2
		}, {
			"name": "用户管理",
			"icon": "ico193",
			"auth": "FG_MEMU_SYSTEM_USERMANAGE",
			"url": "model/operations/userManage.html",
			"mid": "userManage",
			"l": 2
		}, {
			"name": "公告管理",
			"icon": "ico189",
			"auth": "FG_MEMU_SYSTEM_CORPMESSAGEMANAGE",
			"url": "model/operations/corpMessageManage.html",
			"mid": "corpMessageManage",
			"l": 2
		}, {
			/*"name": "授权管理",
					      "icon": "ico189",
					      "auth": "FG_MEMU_MANAGER_BULLETIN",
					      "url": "model/operations/grantManage.html",
					      "mid": "grantManage",
					      "l": 2
					    },{*/
			"name": "系统设置",
			"icon": "ico189",
			"auth": "FG_MEMU_SYSTEM_SALESTAT",
			"url": "model/operations/saleStat.html",
			"mid": "saleStat",
			"l": 2
		}, {
			"name": "个人资料",
			"icon": "ico189",
			"auth": "FG_MEMU_SYSTEM_PERSONALPROFILE",
			"url": "model/operations/personalProfile.html",
			"mid": "personalProfile",
			"l": 2
		}, {
		// 	"name": "公司概要",
		// 	"icon": "ico189",
		// 	"auth": "FG_MEMU_SYSTEM_COMPANYPROFILE",
		// 	"url": "model/operations/companyProfile.html",
		// 	"mid": "companyProfile",
		// 	"l": 2
		// }, {
			"name": "操作记录",
			"icon": "ico189",
			"auth": "FG_MEMU_SYSTEM_OPERATERLOGMANAGE",
			"url": "model/operations/operaterLogManage.html",
			"mid": "operaterLogManage",
			"l": 2
		}]
	}]
};