############################################################
## makefile of libunisql.a
############################################################
.SUFFIXES: .cpp

SOURCES  = 	../share/xml/httpcaller.cpp ../share/cache/msgcache.cpp pasclient.cpp pconvert.cpp  msgclient.cpp systemenv.cpp pccmain.cpp 
#SOURCES = testmain.cpp           
PROGRAM  = pcc_fujian
CLIB     = 

SPECIAL_MACRO_FLAGS = 
SPECIAL_CCFLAGS = 
SPECIAL_INCL_PATH = -I../include -I../share/node -I../share/xml -I../share/cache
SPECIAL_LIB_PATH = 
SPECIAL_MACRO_FLAGS = 

SPECIAL_LIBS = -lctfobase

include ${MTRANS_PRJ_HOME}/makefile.include
