############################################################
## makefile of libunisql.a
############################################################
.SUFFIXES: .cpp

SOURCES  = msgclient.cpp systemenv.cpp main.cpp 
#SOURCES = testmain.cpp           
PROGRAM  = dispatcher_pic
CLIB     = 

SPECIAL_MACRO_FLAGS = 
SPECIAL_CCFLAGS = 
SPECIAL_INCL_PATH = -I../share/node
SPECIAL_LIB_PATH = 
SPECIAL_MACRO_FLAGS = 

SPECIAL_LIBS = -lctfobase

include ${MTRANS_PRJ_HOME}/makefile.include
