############################################################
## makefile of libunisql.a
############################################################
.SUFFIXES: .cpp

SOURCES  = main.cpp
PROGRAM  = test
CLIB     = 

SPECIAL_MACRO_FLAGS  = -DRELEASE -D_MUTIL_MUTEX 
##SPECIAL_MACRO_FLAGS += -D_TESTTHREAD
SPECIAL_CCFLAGS   = 
SPECIAL_INCL_PATH = 
SPECIAL_LIB_PATH  = 

SPECIAL_LIBS = -lctfobase

include ${CTFOLIBS_HOME}/makefile.include
