package com.ctfo.storage.init.model;

import java.io.Serializable;




public class TbSpOperator extends BaseModel implements Serializable{
	
	
    /**
	 * serialVersionUID:long
	 */
	private static final long serialVersionUID = 5207267911718976666L;

	/**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_SP_OPERATOR.OP_ID
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    private String opId = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_SP_OPERATOR.ENT_ID
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    private String entId = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_SP_OPERATOR.OP_LOGINNAME
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    private String opLoginname;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_SP_OPERATOR.OP_PASS
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    private String opPass = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_SP_OPERATOR.OP_AUTHCODE
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    private String opAuthcode = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_SP_OPERATOR.OP_NAME
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    private String opName = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_SP_OPERATOR.OP_SUPER
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    private String opSuper = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_SP_OPERATOR.OP_SEX
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    private String opSex = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_SP_OPERATOR.OP_BIRTH
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    private Long opBirth = -1l;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_SP_OPERATOR.OP_COUNTRY
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    private String opCountry = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_SP_OPERATOR.OP_PROVINCE
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    private String opProvince = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_SP_OPERATOR.OP_CITY
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    private String opCity = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_SP_OPERATOR.OP_ADDRESS
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    private String opAddress = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_SP_OPERATOR.OP_MOBILE
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    private String opMobile = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_SP_OPERATOR.OP_PHONE
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    private String opPhone = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_SP_OPERATOR.OP_FAX
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    private String opFax = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_SP_OPERATOR.OP_EMAIL
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    private String opEmail = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_SP_OPERATOR.OP_IDENTITY_ID
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    private String opIdentityId = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_SP_OPERATOR.OP_DUTY
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    private String opDuty = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_SP_OPERATOR.OP_WORKID
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    private String opWorkid = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_SP_OPERATOR.OP_STARTUTC
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    private Long opStartutc = -1l;
    
    
    private Long opEndutc =-1l;////////////账号失效日期

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_SP_OPERATOR.OP_TYPE
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    private String opType = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_SP_OPERATOR.OP_MEM
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    private String opMem = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_SP_OPERATOR.CREATE_BY
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    private String createBy ="";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_SP_OPERATOR.CREATE_TIME
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    private Long createTime =-1l;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_SP_OPERATOR.UPDATE_BY
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    private String updateBy ;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_SP_OPERATOR.UPDATE_TIME
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    private Long updateTime=-1l;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_SP_OPERATOR.ENABLE_FLAG
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    private String enableFlag = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_SP_OPERATOR.OP_ZIP
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    private String opZip = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_SP_OPERATOR.OP_STATUS
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    private String opStatus = "";

    
    
    private String corpCode = "";//企业代码
    
    private String opUnName = "";//创建人名�?
    
    private String entName = "";//�?��企业名称�?
    
    private String roleName = "";//�?��角色
    
    private Long 	roleId = -1l;//角色Id
    
    private String opBirthStr = "";//用户生日字符�?
    
    private String iPAddress = "";//用户登录地址
    
    private Long parentEntId =-1l;//企业父id
    
    private int entType =-1;//组织类型
    
    private String entState = "";//企业状�?
	// 企业logo url
    private String orgLogo = "";
    
    private String seqCode = "";
    
    private String isMember = "";//是否是会�?  0：不�?   1：是
    
    private String imsi = ""; //IMSI号码
    
    private String photo = "";//会员照片
    
    private String httpPhotoPath = "";//页面显示路径
    
    private String businessLicense = ""; //企业经营许可证号
    
    private String loginSessionId = "";

    /**用户在线情况使用**/
    private String sysType = "";//登录系统 0|管理系统�?|应用系统
    
    private Long  loginSysTime =-1l;//登录时间
    
    private Long  loginCount =-1l;//标示该账号同时有几处在登�?
    
    private String skinStyle = "";//换肤皮肤样式
    /**
     * 是否为数据中心用户（1：分中心用户，0：数据中心用户，默认为1，分中心用户）
     */
    private int isCenter = 1;
    
    
    
    /**
	 * 获取是否为数据中心用户（1：分中心用户，0：数据中心用户，默认为1，分中心用户）的值
	 * @return isCenter  
	 */
	public int getIsCenter() {
		return isCenter;
	}

	/**
	 * 设置是否为数据中心用户（1：分中心用户，0：数据中心用户，默认为1，分中心用户）的值
	 * @param isCenter
	 */
	public void setIsCenter(int isCenter) {
		this.isCenter = isCenter;
	}

	/**
	 * 获取iPAddress的值
	 * @return iPAddress  
	 */
	public String getiPAddress() {
		return iPAddress;
	}

	/**
	 * 设置iPAddress的值
	 * @param iPAddress
	 */
	public void setiPAddress(String iPAddress) {
		this.iPAddress = iPAddress;
	}

	/**
	 * 获取skinStyle的值
	 * @return skinStyle  
	 */
	public String getSkinStyle() {
		return skinStyle;
	}

	/**
	 * 设置skinStyle的值
	 * @param skinStyle
	 */
	public void setSkinStyle(String skinStyle) {
		this.skinStyle = skinStyle;
	}

	public Long getLoginCount() {
		return loginCount;
	}

	public void setLoginCount(Long loginCount) {
		this.loginCount = loginCount;
	}

	public Long getOpEndutc() {
		return opEndutc;
	}

	public void setOpEndutc(Long opEndutc) {
		this.opEndutc = opEndutc;
	}

	public String getHttpPhotoPath() {
		return httpPhotoPath;
	}

	public void setHttpPhotoPath(String httpPhotoPath) {
		this.httpPhotoPath = httpPhotoPath;
	}

	public String getPhoto() {
		return photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	public String getIsMember() {
		return isMember;
	}

	public void setIsMember(String isMember) {
		this.isMember = isMember;
	}

	public String getImsi() {
		return imsi;
	}

	public void setImsi(String imsi) {
		this.imsi = imsi;
	}

	public String getOpBirthStr() {
		return opBirthStr;
	}

	public void setOpBirthStr(String opBirthStr) {
		this.opBirthStr = opBirthStr;
	}

	public Long getRoleId() {
		return roleId;
	}

	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

	public String getCorpCode() {
		return corpCode;
	}

	public void setCorpCode(String corpCode) {
		this.corpCode = corpCode;
	}

	public String getOpUnName() {
		return opUnName;
	}

	public void setOpUnName(String opUnName) {
		this.opUnName = opUnName;
	}

	public String getEntName() {
		return entName;
	}

	public void setEntName(String entName) {
		this.entName = entName;
	}

	public String getRoleName() {
		return roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	/**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_SP_OPERATOR.OP_ID
     *
     * @return the value of SYS_SP_OPERATOR.OP_ID
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public String getOpId() {
        return opId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_SP_OPERATOR.OP_ID
     *
     * @param opId the value for SYS_SP_OPERATOR.OP_ID
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public void setOpId(String opId) {
        this.opId = opId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_SP_OPERATOR.ENT_ID
     *
     * @return the value of SYS_SP_OPERATOR.ENT_ID
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public String getEntId() {
        return entId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_SP_OPERATOR.ENT_ID
     *
     * @param entId the value for SYS_SP_OPERATOR.ENT_ID
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public void setEntId(String entId) {
        this.entId = entId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_SP_OPERATOR.OP_LOGINNAME
     *
     * @return the value of SYS_SP_OPERATOR.OP_LOGINNAME
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public String getOpLoginname() {
        return opLoginname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_SP_OPERATOR.OP_LOGINNAME
     *
     * @param opLoginname the value for SYS_SP_OPERATOR.OP_LOGINNAME
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public void setOpLoginname(String opLoginname) {
        this.opLoginname = opLoginname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_SP_OPERATOR.OP_PASS
     *
     * @return the value of SYS_SP_OPERATOR.OP_PASS
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public String getOpPass() {
        return opPass;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_SP_OPERATOR.OP_PASS
     *
     * @param opPass the value for SYS_SP_OPERATOR.OP_PASS
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public void setOpPass(String opPass) {
        this.opPass = opPass;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_SP_OPERATOR.OP_AUTHCODE
     *
     * @return the value of SYS_SP_OPERATOR.OP_AUTHCODE
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public String getOpAuthcode() {
        return opAuthcode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_SP_OPERATOR.OP_AUTHCODE
     *
     * @param opAuthcode the value for SYS_SP_OPERATOR.OP_AUTHCODE
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public void setOpAuthcode(String opAuthcode) {
        this.opAuthcode = opAuthcode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_SP_OPERATOR.OP_NAME
     *
     * @return the value of SYS_SP_OPERATOR.OP_NAME
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public String getOpName() {
        return opName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_SP_OPERATOR.OP_NAME
     *
     * @param opName the value for SYS_SP_OPERATOR.OP_NAME
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public void setOpName(String opName) {
        this.opName = opName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_SP_OPERATOR.OP_SUPER
     *
     * @return the value of SYS_SP_OPERATOR.OP_SUPER
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public String getOpSuper() {
        return opSuper;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_SP_OPERATOR.OP_SUPER
     *
     * @param opSuper the value for SYS_SP_OPERATOR.OP_SUPER
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public void setOpSuper(String opSuper) {
        this.opSuper = opSuper;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_SP_OPERATOR.OP_SEX
     *
     * @return the value of SYS_SP_OPERATOR.OP_SEX
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public String getOpSex() {
        return opSex;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_SP_OPERATOR.OP_SEX
     *
     * @param opSex the value for SYS_SP_OPERATOR.OP_SEX
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public void setOpSex(String opSex) {
        this.opSex = opSex;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_SP_OPERATOR.OP_BIRTH
     *
     * @return the value of SYS_SP_OPERATOR.OP_BIRTH
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public Long getOpBirth() {
        return opBirth;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_SP_OPERATOR.OP_BIRTH
     *
     * @param opBirth the value for SYS_SP_OPERATOR.OP_BIRTH
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public void setOpBirth(Long opBirth) {
        this.opBirth = opBirth;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_SP_OPERATOR.OP_COUNTRY
     *
     * @return the value of SYS_SP_OPERATOR.OP_COUNTRY
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public String getOpCountry() {
        return opCountry;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_SP_OPERATOR.OP_COUNTRY
     *
     * @param opCountry the value for SYS_SP_OPERATOR.OP_COUNTRY
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public void setOpCountry(String opCountry) {
        this.opCountry = opCountry;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_SP_OPERATOR.OP_PROVINCE
     *
     * @return the value of SYS_SP_OPERATOR.OP_PROVINCE
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public String getOpProvince() {
        return opProvince;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_SP_OPERATOR.OP_PROVINCE
     *
     * @param opProvince the value for SYS_SP_OPERATOR.OP_PROVINCE
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public void setOpProvince(String opProvince) {
        this.opProvince = opProvince;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_SP_OPERATOR.OP_CITY
     *
     * @return the value of SYS_SP_OPERATOR.OP_CITY
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public String getOpCity() {
        return opCity;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_SP_OPERATOR.OP_CITY
     *
     * @param opCity the value for SYS_SP_OPERATOR.OP_CITY
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public void setOpCity(String opCity) {
        this.opCity = opCity;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_SP_OPERATOR.OP_ADDRESS
     *
     * @return the value of SYS_SP_OPERATOR.OP_ADDRESS
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public String getOpAddress() {
        return opAddress;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_SP_OPERATOR.OP_ADDRESS
     *
     * @param opAddress the value for SYS_SP_OPERATOR.OP_ADDRESS
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public void setOpAddress(String opAddress) {
        this.opAddress = opAddress;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_SP_OPERATOR.OP_MOBILE
     *
     * @return the value of SYS_SP_OPERATOR.OP_MOBILE
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public String getOpMobile() {
        return opMobile;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_SP_OPERATOR.OP_MOBILE
     *
     * @param opMobile the value for SYS_SP_OPERATOR.OP_MOBILE
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public void setOpMobile(String opMobile) {
        this.opMobile = opMobile;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_SP_OPERATOR.OP_PHONE
     *
     * @return the value of SYS_SP_OPERATOR.OP_PHONE
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public String getOpPhone() {
        return opPhone;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_SP_OPERATOR.OP_PHONE
     *
     * @param opPhone the value for SYS_SP_OPERATOR.OP_PHONE
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public void setOpPhone(String opPhone) {
        this.opPhone = opPhone;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_SP_OPERATOR.OP_FAX
     *
     * @return the value of SYS_SP_OPERATOR.OP_FAX
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public String getOpFax() {
        return opFax;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_SP_OPERATOR.OP_FAX
     *
     * @param opFax the value for SYS_SP_OPERATOR.OP_FAX
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public void setOpFax(String opFax) {
        this.opFax = opFax;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_SP_OPERATOR.OP_EMAIL
     *
     * @return the value of SYS_SP_OPERATOR.OP_EMAIL
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public String getOpEmail() {
        return opEmail;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_SP_OPERATOR.OP_EMAIL
     *
     * @param opEmail the value for SYS_SP_OPERATOR.OP_EMAIL
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public void setOpEmail(String opEmail) {
        this.opEmail = opEmail;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_SP_OPERATOR.OP_IDENTITY_ID
     *
     * @return the value of SYS_SP_OPERATOR.OP_IDENTITY_ID
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public String getOpIdentityId() {
        return opIdentityId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_SP_OPERATOR.OP_IDENTITY_ID
     *
     * @param opIdentityId the value for SYS_SP_OPERATOR.OP_IDENTITY_ID
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public void setOpIdentityId(String opIdentityId) {
        this.opIdentityId = opIdentityId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_SP_OPERATOR.OP_DUTY
     *
     * @return the value of SYS_SP_OPERATOR.OP_DUTY
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public String getOpDuty() {
        return opDuty;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_SP_OPERATOR.OP_DUTY
     *
     * @param opDuty the value for SYS_SP_OPERATOR.OP_DUTY
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public void setOpDuty(String opDuty) {
        this.opDuty = opDuty;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_SP_OPERATOR.OP_WORKID
     *
     * @return the value of SYS_SP_OPERATOR.OP_WORKID
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public String getOpWorkid() {
        return opWorkid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_SP_OPERATOR.OP_WORKID
     *
     * @param opWorkid the value for SYS_SP_OPERATOR.OP_WORKID
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public void setOpWorkid(String opWorkid) {
        this.opWorkid = opWorkid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_SP_OPERATOR.OP_STARTUTC
     *
     * @return the value of SYS_SP_OPERATOR.OP_STARTUTC
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public Long getOpStartutc() {
        return opStartutc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_SP_OPERATOR.OP_STARTUTC
     *
     * @param opStartutc the value for SYS_SP_OPERATOR.OP_STARTUTC
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public void setOpStartutc(Long opStartutc) {
        this.opStartutc = opStartutc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_SP_OPERATOR.OP_TYPE
     *
     * @return the value of SYS_SP_OPERATOR.OP_TYPE
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public String getOpType() {
        return opType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_SP_OPERATOR.OP_TYPE
     *
     * @param opType the value for SYS_SP_OPERATOR.OP_TYPE
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public void setOpType(String opType) {
        this.opType = opType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_SP_OPERATOR.OP_MEM
     *
     * @return the value of SYS_SP_OPERATOR.OP_MEM
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public String getOpMem() {
        return opMem;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_SP_OPERATOR.OP_MEM
     *
     * @param opMem the value for SYS_SP_OPERATOR.OP_MEM
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public void setOpMem(String opMem) {
        this.opMem = opMem;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_SP_OPERATOR.CREATE_BY
     *
     * @return the value of SYS_SP_OPERATOR.CREATE_BY
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_SP_OPERATOR.CREATE_BY
     *
     * @param createBy the value for SYS_SP_OPERATOR.CREATE_BY
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_SP_OPERATOR.CREATE_TIME
     *
     * @return the value of SYS_SP_OPERATOR.CREATE_TIME
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_SP_OPERATOR.CREATE_TIME
     *
     * @param createTime the value for SYS_SP_OPERATOR.CREATE_TIME
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_SP_OPERATOR.UPDATE_BY
     *
     * @return the value of SYS_SP_OPERATOR.UPDATE_BY
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_SP_OPERATOR.UPDATE_BY
     *
     * @param updateBy the value for SYS_SP_OPERATOR.UPDATE_BY
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_SP_OPERATOR.UPDATE_TIME
     *
     * @return the value of SYS_SP_OPERATOR.UPDATE_TIME
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_SP_OPERATOR.UPDATE_TIME
     *
     * @param updateTime the value for SYS_SP_OPERATOR.UPDATE_TIME
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_SP_OPERATOR.ENABLE_FLAG
     *
     * @return the value of SYS_SP_OPERATOR.ENABLE_FLAG
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public String getEnableFlag() {
        return enableFlag;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_SP_OPERATOR.ENABLE_FLAG
     *
     * @param enableFlag the value for SYS_SP_OPERATOR.ENABLE_FLAG
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public void setEnableFlag(String enableFlag) {
        this.enableFlag = enableFlag;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_SP_OPERATOR.OP_ZIP
     *
     * @return the value of SYS_SP_OPERATOR.OP_ZIP
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public String getOpZip() {
        return opZip;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_SP_OPERATOR.OP_ZIP
     *
     * @param opZip the value for SYS_SP_OPERATOR.OP_ZIP
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public void setOpZip(String opZip) {
        this.opZip = opZip;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_SP_OPERATOR.OP_STATUS
     *
     * @return the value of SYS_SP_OPERATOR.OP_STATUS
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public String getOpStatus() {
        return opStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_SP_OPERATOR.OP_STATUS
     *
     * @param opStatus the value for SYS_SP_OPERATOR.OP_STATUS
     *
     * @abatorgenerated Sat Oct 08 10:33:44 CST 2011
     */
    public void setOpStatus(String opStatus) {
        this.opStatus = opStatus;
    }

	public String getIPAddress() {
		return iPAddress;
	}

	public void setIPAddress(String iPAddress) {
		this.iPAddress = iPAddress;
	}

	public Long getParentEntId() {
		return parentEntId;
	}

	public void setParentEntId(Long parentEntId) {
		this.parentEntId = parentEntId;
	}

	public int getEntType() {
		return entType;
	}

	public void setEntType(int entType) {
		this.entType = entType;
	}

	public String getEntState() {
		return entState;
	}

	public void setEntState(String entState) {
		this.entState = entState;
	}

	public String getOrgLogo() {
		return orgLogo;
	}

	public void setOrgLogo(String orgLogo) {
		this.orgLogo = orgLogo;
	}

	public String getSeqCode() {
		return seqCode;
	}

	public void setSeqCode(String seqCode) {
		this.seqCode = seqCode;
	}

	public String getBusinessLicense() {
		return businessLicense;
	}

	public void setBusinessLicense(String businessLicense) {
		this.businessLicense = businessLicense;
	}

	public String getSysType() {
		return sysType;
	}

	public void setSysType(String sysType) {
		this.sysType = sysType;
	}

	public Long getLoginSysTime() {
		return loginSysTime;
	}

	public void setLoginSysTime(Long loginSysTime) {
		this.loginSysTime = loginSysTime;
	}

	public String getLoginSessionId() {
		return loginSessionId;
	}

	public void setLoginSessionId(String loginSessionId) {
		this.loginSessionId = loginSessionId;
	}

	

	

	
	
}