package com.ctfo.storage.init.model;



import java.io.Serializable;


public class TbTerminalOem extends BaseModel implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_TERMINAL_OEM.OEM_CODE
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    private String oemCode = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_TERMINAL_OEM.FULL_NAME
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    private String fullName = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_TERMINAL_OEM.SHORT_NAME
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    private String shortName = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_TERMINAL_OEM.ADDRESS
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    private String address = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_TERMINAL_OEM.OEM_DESC
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    private String oemDesc = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_TERMINAL_OEM.OEM_TYPE
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    private String oemType = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_TERMINAL_OEM.ENTERPRISE_COUNTRY
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    private String enterpriseCountry = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_TERMINAL_OEM.ENTERPRISE_PROVINCE
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    private String enterpriseProvince = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_TERMINAL_OEM.ENTERPRISE_CITY
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    private String enterpriseCity = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_TERMINAL_OEM.CONCATE_ADDRESS
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    private String concateAddress = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_TERMINAL_OEM.WEB_ADDRESS
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    private String webAddress = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_TERMINAL_OEM.BOSS
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    private String boss = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_TERMINAL_OEM.ZIP_CODE
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    private String zipCode = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_TERMINAL_OEM.CONCATE_PERSON
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    private String concatePerson = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_TERMINAL_OEM.CELLPHONE
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    private String cellphone = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_TERMINAL_OEM.TEL
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    private String tel = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_TERMINAL_OEM.EMAIL
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    private String email = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_TERMINAL_OEM.CREATE_BY
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    private String createBy = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_TERMINAL_OEM.CREATE_TIME
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    private String createTime = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_TERMINAL_OEM.UPDATE_BY
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    private String updateBy = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_TERMINAL_OEM.FAX
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    private String fax = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_TERMINAL_OEM.UPDATE_TIME
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    private String updateTime = "";

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_TERMINAL_OEM.ENABLE_FLAG
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    private String enableFlag = "";

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_TERMINAL_OEM.OEM_CODE
     *
     * @return the value of SYS_TERMINAL_OEM.OEM_CODE
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    public String getOemCode() {
        return oemCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_TERMINAL_OEM.OEM_CODE
     *
     * @param oemCode the value for SYS_TERMINAL_OEM.OEM_CODE
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    public void setOemCode(String oemCode) {
        this.oemCode = oemCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_TERMINAL_OEM.FULL_NAME
     *
     * @return the value of SYS_TERMINAL_OEM.FULL_NAME
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_TERMINAL_OEM.FULL_NAME
     *
     * @param fullName the value for SYS_TERMINAL_OEM.FULL_NAME
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_TERMINAL_OEM.SHORT_NAME
     *
     * @return the value of SYS_TERMINAL_OEM.SHORT_NAME
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_TERMINAL_OEM.SHORT_NAME
     *
     * @param shortName the value for SYS_TERMINAL_OEM.SHORT_NAME
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    public void setShortName(String shortName) {
        this.shortName = shortName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_TERMINAL_OEM.ADDRESS
     *
     * @return the value of SYS_TERMINAL_OEM.ADDRESS
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_TERMINAL_OEM.ADDRESS
     *
     * @param address the value for SYS_TERMINAL_OEM.ADDRESS
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_TERMINAL_OEM.OEM_DESC
     *
     * @return the value of SYS_TERMINAL_OEM.OEM_DESC
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    public String getOemDesc() {
        return oemDesc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_TERMINAL_OEM.OEM_DESC
     *
     * @param oemDesc the value for SYS_TERMINAL_OEM.OEM_DESC
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    public void setOemDesc(String oemDesc) {
        this.oemDesc = oemDesc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_TERMINAL_OEM.OEM_TYPE
     *
     * @return the value of SYS_TERMINAL_OEM.OEM_TYPE
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    public String getOemType() {
        return oemType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_TERMINAL_OEM.OEM_TYPE
     *
     * @param oemType the value for SYS_TERMINAL_OEM.OEM_TYPE
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    public void setOemType(String oemType) {
        this.oemType = oemType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_TERMINAL_OEM.ENTERPRISE_COUNTRY
     *
     * @return the value of SYS_TERMINAL_OEM.ENTERPRISE_COUNTRY
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    public String getEnterpriseCountry() {
        return enterpriseCountry;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_TERMINAL_OEM.ENTERPRISE_COUNTRY
     *
     * @param enterpriseCountry the value for SYS_TERMINAL_OEM.ENTERPRISE_COUNTRY
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    public void setEnterpriseCountry(String enterpriseCountry) {
        this.enterpriseCountry = enterpriseCountry;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_TERMINAL_OEM.ENTERPRISE_PROVINCE
     *
     * @return the value of SYS_TERMINAL_OEM.ENTERPRISE_PROVINCE
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    public String getEnterpriseProvince() {
        return enterpriseProvince;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_TERMINAL_OEM.ENTERPRISE_PROVINCE
     *
     * @param enterpriseProvince the value for SYS_TERMINAL_OEM.ENTERPRISE_PROVINCE
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    public void setEnterpriseProvince(String enterpriseProvince) {
        this.enterpriseProvince = enterpriseProvince;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_TERMINAL_OEM.ENTERPRISE_CITY
     *
     * @return the value of SYS_TERMINAL_OEM.ENTERPRISE_CITY
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    public String getEnterpriseCity() {
        return enterpriseCity;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_TERMINAL_OEM.ENTERPRISE_CITY
     *
     * @param enterpriseCity the value for SYS_TERMINAL_OEM.ENTERPRISE_CITY
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    public void setEnterpriseCity(String enterpriseCity) {
        this.enterpriseCity = enterpriseCity;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_TERMINAL_OEM.CONCATE_ADDRESS
     *
     * @return the value of SYS_TERMINAL_OEM.CONCATE_ADDRESS
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    public String getConcateAddress() {
        return concateAddress;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_TERMINAL_OEM.CONCATE_ADDRESS
     *
     * @param concateAddress the value for SYS_TERMINAL_OEM.CONCATE_ADDRESS
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    public void setConcateAddress(String concateAddress) {
        this.concateAddress = concateAddress;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_TERMINAL_OEM.WEB_ADDRESS
     *
     * @return the value of SYS_TERMINAL_OEM.WEB_ADDRESS
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    public String getWebAddress() {
        return webAddress;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_TERMINAL_OEM.WEB_ADDRESS
     *
     * @param webAddress the value for SYS_TERMINAL_OEM.WEB_ADDRESS
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    public void setWebAddress(String webAddress) {
        this.webAddress = webAddress;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_TERMINAL_OEM.BOSS
     *
     * @return the value of SYS_TERMINAL_OEM.BOSS
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    public String getBoss() {
        return boss;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_TERMINAL_OEM.BOSS
     *
     * @param boss the value for SYS_TERMINAL_OEM.BOSS
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    public void setBoss(String boss) {
        this.boss = boss;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_TERMINAL_OEM.ZIP_CODE
     *
     * @return the value of SYS_TERMINAL_OEM.ZIP_CODE
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_TERMINAL_OEM.ZIP_CODE
     *
     * @param zipCode the value for SYS_TERMINAL_OEM.ZIP_CODE
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_TERMINAL_OEM.CONCATE_PERSON
     *
     * @return the value of SYS_TERMINAL_OEM.CONCATE_PERSON
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    public String getConcatePerson() {
        return concatePerson;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_TERMINAL_OEM.CONCATE_PERSON
     *
     * @param concatePerson the value for SYS_TERMINAL_OEM.CONCATE_PERSON
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    public void setConcatePerson(String concatePerson) {
        this.concatePerson = concatePerson;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_TERMINAL_OEM.CELLPHONE
     *
     * @return the value of SYS_TERMINAL_OEM.CELLPHONE
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    public String getCellphone() {
        return cellphone;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_TERMINAL_OEM.CELLPHONE
     *
     * @param cellphone the value for SYS_TERMINAL_OEM.CELLPHONE
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    public void setCellphone(String cellphone) {
        this.cellphone = cellphone;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_TERMINAL_OEM.TEL
     *
     * @return the value of SYS_TERMINAL_OEM.TEL
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_TERMINAL_OEM.TEL
     *
     * @param tel the value for SYS_TERMINAL_OEM.TEL
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_TERMINAL_OEM.EMAIL
     *
     * @return the value of SYS_TERMINAL_OEM.EMAIL
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_TERMINAL_OEM.EMAIL
     *
     * @param email the value for SYS_TERMINAL_OEM.EMAIL
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_TERMINAL_OEM.CREATE_BY
     *
     * @return the value of SYS_TERMINAL_OEM.CREATE_BY
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_TERMINAL_OEM.CREATE_BY
     *
     * @param createBy the value for SYS_TERMINAL_OEM.CREATE_BY
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_TERMINAL_OEM.CREATE_TIME
     *
     * @return the value of SYS_TERMINAL_OEM.CREATE_TIME
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_TERMINAL_OEM.CREATE_TIME
     *
     * @param createTime the value for SYS_TERMINAL_OEM.CREATE_TIME
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_TERMINAL_OEM.UPDATE_BY
     *
     * @return the value of SYS_TERMINAL_OEM.UPDATE_BY
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_TERMINAL_OEM.UPDATE_BY
     *
     * @param updateBy the value for SYS_TERMINAL_OEM.UPDATE_BY
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_TERMINAL_OEM.FAX
     *
     * @return the value of SYS_TERMINAL_OEM.FAX
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_TERMINAL_OEM.FAX
     *
     * @param fax the value for SYS_TERMINAL_OEM.FAX
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    public void setFax(String fax) {
        this.fax = fax;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_TERMINAL_OEM.UPDATE_TIME
     *
     * @return the value of SYS_TERMINAL_OEM.UPDATE_TIME
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_TERMINAL_OEM.UPDATE_TIME
     *
     * @param updateTime the value for SYS_TERMINAL_OEM.UPDATE_TIME
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_TERMINAL_OEM.ENABLE_FLAG
     *
     * @return the value of SYS_TERMINAL_OEM.ENABLE_FLAG
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    public String getEnableFlag() {
        return enableFlag;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_TERMINAL_OEM.ENABLE_FLAG
     *
     * @param enableFlag the value for SYS_TERMINAL_OEM.ENABLE_FLAG
     *
     * @abatorgenerated Tue Oct 18 20:02:47 CST 2011
     */
    public void setEnableFlag(String enableFlag) {
        this.enableFlag = enableFlag;
    }
}