/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.ocean.socket.thrift.server;

import java.util.HashMap;
import java.util.Map;


public class TutorialConstants {

	/**
	 * Thrift also lets you define constants for use across languages. Complex
	 * types and structs are specified using JSON notation.
	 */
	public static final int INT32CONSTANT = 9853;

	public static final Map<String, String> MAPCONSTANT = new HashMap<String, String>();
	static {
		MAPCONSTANT.put("hello", "world");
		MAPCONSTANT.put("goodnight", "moon");
	}

}
