############################################################
## makefile of libunisql.a
############################################################
.SUFFIXES: .cpp

SOURCES  = cConfig.cpp tools.cpp utility.cpp main_app.cpp Base64.cpp
#mem_alloc.cpp
PROGRAM  = 
#CLIB     = libutils.a 
LIBS     =
SONAME   = libutils.so.2
LNNAME   = libutils.so

include ${CTFOLIBS_HOME}/makefile.include

