############################################################
## makefile of libunisql.a
############################################################
.SUFFIXES: .cpp

SOURCES  = 	mybase64.cpp pasclient.cpp pccsession.cpp pconvert.cpp msgclient.cpp busloader.cpp 
SOURCES +=  msgcache.cpp usermgr.cpp passerver.cpp statinfo.cpp systemenv.cpp pccmain.cpp 
#SOURCES = testmain.cpp           
PROGRAM  = pcc_jiangsu
CLIB     = 

SPECIAL_MACRO_FLAGS = 
SPECIAL_CCFLAGS = 
SPECIAL_INCL_PATH = -I../share/node
SPECIAL_LIB_PATH = 
SPECIAL_MACRO_FLAGS = 

SPECIAL_LIBS = -lctfobase

include ${MTRANS_PRJ_HOME}/makefile.include
