package com.ctfo.sys.dao.impl;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.ctfo.sys.beans.SysGeneralCode;
import com.ctfo.sys.dao.SysGeneralCodeDAO;

public class SysGeneralCodeDAOImpl extends SqlMapClientDaoSupport implements SysGeneralCodeDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SYS_GENERAL_CODE
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	public SysGeneralCodeDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SYS_GENERAL_CODE
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	public void insert(SysGeneralCode record) {
		getSqlMapClientTemplate().insert("SYS_GENERAL_CODE.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SYS_GENERAL_CODE
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	public int updateByPrimaryKey(SysGeneralCode record) {
		int rows = getSqlMapClientTemplate().update("SYS_GENERAL_CODE.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SYS_GENERAL_CODE
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	public int updateByPrimaryKeySelective(SysGeneralCode record) {
		int rows = getSqlMapClientTemplate().update("SYS_GENERAL_CODE.abatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SYS_GENERAL_CODE
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	public SysGeneralCode selectByPrimaryKey(String autoId) {
		SysGeneralCode key = new SysGeneralCode();
		key.setAutoId(autoId);
		SysGeneralCode record = (SysGeneralCode) getSqlMapClientTemplate().queryForObject("SYS_GENERAL_CODE.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SYS_GENERAL_CODE
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	public int deleteByPrimaryKey(String autoId) {
		SysGeneralCode key = new SysGeneralCode();
		key.setAutoId(autoId);
		int rows = getSqlMapClientTemplate().delete("SYS_GENERAL_CODE.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

}