package com.ctfo.sys.dao.impl;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.ctfo.sys.beans.SysSkin;
import com.ctfo.sys.dao.SysSkinDAO;

public class SysSkinDAOImpl extends SqlMapClientDaoSupport implements SysSkinDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SYS_SKIN
	 * @abatorgenerated  Mon Mar 24 16:46:48 CST 2014
	 */
	public SysSkinDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SYS_SKIN
	 * @abatorgenerated  Mon Mar 24 16:46:48 CST 2014
	 */
	public void insert(SysSkin record) {
		getSqlMapClientTemplate().insert("SYS_SKIN.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SYS_SKIN
	 * @abatorgenerated  Mon Mar 24 16:46:48 CST 2014
	 */
	public int updateByPrimaryKey(SysSkin record) {
		int rows = getSqlMapClientTemplate().update("SYS_SKIN.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SYS_SKIN
	 * @abatorgenerated  Mon Mar 24 16:46:48 CST 2014
	 */
	public int updateByPrimaryKeySelective(SysSkin record) {
		int rows = getSqlMapClientTemplate().update("SYS_SKIN.abatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SYS_SKIN
	 * @abatorgenerated  Mon Mar 24 16:46:48 CST 2014
	 */
	public SysSkin selectByPrimaryKey(String skinCode) {
		SysSkin key = new SysSkin();
		key.setSkinCode(skinCode);
		SysSkin record = (SysSkin) getSqlMapClientTemplate().queryForObject("SYS_SKIN.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SYS_SKIN
	 * @abatorgenerated  Mon Mar 24 16:46:48 CST 2014
	 */
	public int deleteByPrimaryKey(String skinCode) {
		SysSkin key = new SysSkin();
		key.setSkinCode(skinCode);
		int rows = getSqlMapClientTemplate().delete("SYS_SKIN.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}
}