package com.ctfo.sys.dao.impl;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.ctfo.sys.beans.TrOperatorPosition;
import com.ctfo.sys.dao.TrOperatorPositionDAO;

public class TrOperatorPositionDAOImpl extends SqlMapClientDaoSupport implements TrOperatorPositionDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TR_OPERATOR_POSITION
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public TrOperatorPositionDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TR_OPERATOR_POSITION
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public void insert(TrOperatorPosition record) {
		getSqlMapClientTemplate().insert("TR_OPERATOR_POSITION.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TR_OPERATOR_POSITION
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public int updateByPrimaryKey(TrOperatorPosition record) {
		int rows = getSqlMapClientTemplate().update("TR_OPERATOR_POSITION.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TR_OPERATOR_POSITION
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public int updateByPrimaryKeySelective(TrOperatorPosition record) {
		int rows = getSqlMapClientTemplate().update("TR_OPERATOR_POSITION.abatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TR_OPERATOR_POSITION
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public TrOperatorPosition selectByPrimaryKey(String autoId) {
		TrOperatorPosition key = new TrOperatorPosition();
		key.setAutoId(autoId);
		TrOperatorPosition record = (TrOperatorPosition) getSqlMapClientTemplate().queryForObject("TR_OPERATOR_POSITION.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TR_OPERATOR_POSITION
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public int deleteByPrimaryKey(String autoId) {
		TrOperatorPosition key = new TrOperatorPosition();
		key.setAutoId(autoId);
		int rows = getSqlMapClientTemplate().delete("TR_OPERATOR_POSITION.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}
}