package com.ctfo.sys.dao;

import com.ctfo.sys.beans.SysSkin;

public interface SysSkinDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SYS_SKIN
	 * @abatorgenerated  Mon Mar 24 16:46:48 CST 2014
	 */
	void insert(SysSkin record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SYS_SKIN
	 * @abatorgenerated  Mon Mar 24 16:46:48 CST 2014
	 */
	int updateByPrimaryKey(SysSkin record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SYS_SKIN
	 * @abatorgenerated  Mon Mar 24 16:46:48 CST 2014
	 */
	int updateByPrimaryKeySelective(SysSkin record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SYS_SKIN
	 * @abatorgenerated  Mon Mar 24 16:46:48 CST 2014
	 */
	SysSkin selectByPrimaryKey(String skinCode);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table SYS_SKIN
	 * @abatorgenerated  Mon Mar 24 16:46:48 CST 2014
	 */
	int deleteByPrimaryKey(String skinCode);
}