package com.ctfo.sys.dao;

import com.ctfo.sys.beans.TrOperatorPosition;

public interface TrOperatorPositionDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TR_OPERATOR_POSITION
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	void insert(TrOperatorPosition record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TR_OPERATOR_POSITION
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	int updateByPrimaryKey(TrOperatorPosition record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TR_OPERATOR_POSITION
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	int updateByPrimaryKeySelective(TrOperatorPosition record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TR_OPERATOR_POSITION
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	TrOperatorPosition selectByPrimaryKey(String autoId);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TR_OPERATOR_POSITION
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	int deleteByPrimaryKey(String autoId);
}