package com.ctfo.sys.beans;

import java.math.BigDecimal;

public class SysFunction {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_FUNCTION.FUN_ID
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	private String funId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_FUNCTION.FUN_NAME
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	private String funName;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_FUNCTION.FUN_ENAME
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	private String funEname;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_FUNCTION.FUN_URI
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	private String funUri;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_FUNCTION.FUN_IMG
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	private String funImg;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_FUNCTION.FUN_PARENT_ID
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	private String funParentId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_FUNCTION.FUN_CBS
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	private String funCbs;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_FUNCTION.FUN_LEVEL
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	private Short funLevel;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_FUNCTION.FUN_IDX
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	private String funIdx;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_FUNCTION.FUN_FLAG
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	private Short funFlag;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_FUNCTION.FUN_RUN
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	private Short funRun;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_FUNCTION.MEM
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	private String mem;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_FUNCTION.CREATE_BY
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	private BigDecimal createBy;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_FUNCTION.CREATE_TIME
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	private Long createTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_FUNCTION.UPDATE_BY
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	private BigDecimal updateBy;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_FUNCTION.UPDATE_TIME
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	private Long updateTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column SYS_FUNCTION.ENABLE_FLAG
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	private String enableFlag;
	
	private String ischecked;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_FUNCTION.FUN_ID
	 * @return  the value of SYS_FUNCTION.FUN_ID
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	public String getFunId() {
		return funId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_FUNCTION.FUN_ID
	 * @param funId  the value for SYS_FUNCTION.FUN_ID
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	public void setFunId(String funId) {
		this.funId = funId == null ? null : funId.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_FUNCTION.FUN_NAME
	 * @return  the value of SYS_FUNCTION.FUN_NAME
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	public String getFunName() {
		return funName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_FUNCTION.FUN_NAME
	 * @param funName  the value for SYS_FUNCTION.FUN_NAME
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	public void setFunName(String funName) {
		this.funName = funName == null ? null : funName.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_FUNCTION.FUN_ENAME
	 * @return  the value of SYS_FUNCTION.FUN_ENAME
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	public String getFunEname() {
		return funEname;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_FUNCTION.FUN_ENAME
	 * @param funEname  the value for SYS_FUNCTION.FUN_ENAME
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	public void setFunEname(String funEname) {
		this.funEname = funEname == null ? null : funEname.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_FUNCTION.FUN_URI
	 * @return  the value of SYS_FUNCTION.FUN_URI
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	public String getFunUri() {
		return funUri;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_FUNCTION.FUN_URI
	 * @param funUri  the value for SYS_FUNCTION.FUN_URI
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	public void setFunUri(String funUri) {
		this.funUri = funUri == null ? null : funUri.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_FUNCTION.FUN_IMG
	 * @return  the value of SYS_FUNCTION.FUN_IMG
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	public String getFunImg() {
		return funImg;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_FUNCTION.FUN_IMG
	 * @param funImg  the value for SYS_FUNCTION.FUN_IMG
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	public void setFunImg(String funImg) {
		this.funImg = funImg == null ? null : funImg.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_FUNCTION.FUN_PARENT_ID
	 * @return  the value of SYS_FUNCTION.FUN_PARENT_ID
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	public String getFunParentId() {
		return funParentId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_FUNCTION.FUN_PARENT_ID
	 * @param funParentId  the value for SYS_FUNCTION.FUN_PARENT_ID
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	public void setFunParentId(String funParentId) {
		this.funParentId = funParentId == null ? null : funParentId.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_FUNCTION.FUN_CBS
	 * @return  the value of SYS_FUNCTION.FUN_CBS
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	public String getFunCbs() {
		return funCbs;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_FUNCTION.FUN_CBS
	 * @param funCbs  the value for SYS_FUNCTION.FUN_CBS
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	public void setFunCbs(String funCbs) {
		this.funCbs = funCbs == null ? null : funCbs.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_FUNCTION.FUN_LEVEL
	 * @return  the value of SYS_FUNCTION.FUN_LEVEL
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	public Short getFunLevel() {
		return funLevel;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_FUNCTION.FUN_LEVEL
	 * @param funLevel  the value for SYS_FUNCTION.FUN_LEVEL
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	public void setFunLevel(Short funLevel) {
		this.funLevel = funLevel;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_FUNCTION.FUN_IDX
	 * @return  the value of SYS_FUNCTION.FUN_IDX
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	public String getFunIdx() {
		return funIdx;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_FUNCTION.FUN_IDX
	 * @param funIdx  the value for SYS_FUNCTION.FUN_IDX
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	public void setFunIdx(String funIdx) {
		this.funIdx = funIdx == null ? null : funIdx.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_FUNCTION.FUN_FLAG
	 * @return  the value of SYS_FUNCTION.FUN_FLAG
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	public Short getFunFlag() {
		return funFlag;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_FUNCTION.FUN_FLAG
	 * @param funFlag  the value for SYS_FUNCTION.FUN_FLAG
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	public void setFunFlag(Short funFlag) {
		this.funFlag = funFlag;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_FUNCTION.FUN_RUN
	 * @return  the value of SYS_FUNCTION.FUN_RUN
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	public Short getFunRun() {
		return funRun;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_FUNCTION.FUN_RUN
	 * @param funRun  the value for SYS_FUNCTION.FUN_RUN
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	public void setFunRun(Short funRun) {
		this.funRun = funRun;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_FUNCTION.MEM
	 * @return  the value of SYS_FUNCTION.MEM
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	public String getMem() {
		return mem;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_FUNCTION.MEM
	 * @param mem  the value for SYS_FUNCTION.MEM
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	public void setMem(String mem) {
		this.mem = mem == null ? null : mem.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_FUNCTION.CREATE_BY
	 * @return  the value of SYS_FUNCTION.CREATE_BY
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	public BigDecimal getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_FUNCTION.CREATE_BY
	 * @param createBy  the value for SYS_FUNCTION.CREATE_BY
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	public void setCreateBy(BigDecimal createBy) {
		this.createBy = createBy;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_FUNCTION.CREATE_TIME
	 * @return  the value of SYS_FUNCTION.CREATE_TIME
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	public Long getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_FUNCTION.CREATE_TIME
	 * @param createTime  the value for SYS_FUNCTION.CREATE_TIME
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	public void setCreateTime(Long createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_FUNCTION.UPDATE_BY
	 * @return  the value of SYS_FUNCTION.UPDATE_BY
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	public BigDecimal getUpdateBy() {
		return updateBy;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_FUNCTION.UPDATE_BY
	 * @param updateBy  the value for SYS_FUNCTION.UPDATE_BY
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	public void setUpdateBy(BigDecimal updateBy) {
		this.updateBy = updateBy;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_FUNCTION.UPDATE_TIME
	 * @return  the value of SYS_FUNCTION.UPDATE_TIME
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	public Long getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_FUNCTION.UPDATE_TIME
	 * @param updateTime  the value for SYS_FUNCTION.UPDATE_TIME
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	public void setUpdateTime(Long updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column SYS_FUNCTION.ENABLE_FLAG
	 * @return  the value of SYS_FUNCTION.ENABLE_FLAG
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	public String getEnableFlag() {
		return enableFlag;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column SYS_FUNCTION.ENABLE_FLAG
	 * @param enableFlag  the value for SYS_FUNCTION.ENABLE_FLAG
	 * @abatorgenerated  Mon Mar 24 16:46:47 CST 2014
	 */
	public void setEnableFlag(String enableFlag) {
		this.enableFlag = enableFlag == null ? null : enableFlag.trim();
	}

	public String getIschecked() {
		return ischecked;
	}

	public void setIschecked(String ischecked) {
		this.ischecked = ischecked;
	}
	
}