package com.ctfo.sys.beans;

import java.math.BigDecimal;

public class TbOrgInfo {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_ORG_INFO.ENT_ID
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	private String entId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_ORG_INFO.CORP_CODE
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	private String corpCode;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_ORG_INFO.CORP_BUSINESSNO
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	private String corpBusinessno;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_ORG_INFO.SPECIAL_ID
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	private String specialId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_ORG_INFO.BUSINESS_SCOPE
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	private String businessScope;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_ORG_INFO.CERTIFICATE_OFFICE
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	private String certificateOffice;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_ORG_INFO.LICENCE_NO
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	private String licenceNo;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_ORG_INFO.CORP_QUALE
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	private String corpQuale;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_ORG_INFO.CORP_BOSS
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	private BigDecimal corpBoss;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_ORG_INFO.CORP_PAYSTATE
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	private Short corpPaystate;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_ORG_INFO.CORP_PAYTYPE
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	private Short corpPaytype;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_ORG_INFO.CORP_ECONOMYTYPE
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	private String corpEconomytype;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_ORG_INFO.ORG_ADDRESS
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	private String orgAddress;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_ORG_INFO.ORG_CZIP
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	private String orgCzip;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_ORG_INFO.ORG_CFAX
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	private String orgCfax;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_ORG_INFO.URL
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	private String url;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_ORG_INFO.ORG_CMAIL
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	private String orgCmail;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_ORG_INFO.ORG_CNAME
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	private String orgCname;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_ORG_INFO.ORG_CNO
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	private String orgCno;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_ORG_INFO.CREATE_UTC
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	private Long createUtc;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_ORG_INFO.ORG_LOGO
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	private String orgLogo;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_ORG_INFO.ORG_MEM
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	private String orgMem;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_ORG_INFO.ORG_CPHONE
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	private String orgCphone;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_ORG_INFO.ORG_SHORTNAME
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	private String orgShortname;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_ORG_INFO.CORP_COUNTRY
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	private String corpCountry;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_ORG_INFO.CORP_PROVINCE
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	private String corpProvince;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_ORG_INFO.CORP_CITY
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	private String corpCity;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_ORG_INFO.LICENCE_WORD
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	private String licenceWord;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_ORG_INFO.ISDETEAM
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	private String isdeteam;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_ORG_INFO.CORP_LEVEL
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	private String corpLevel;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_ORG_INFO.BUSINESS_LICENSE
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	private String businessLicense;
	
	private Long updateTime;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_ORG_INFO.ENT_ID
	 * @return  the value of TB_ORG_INFO.ENT_ID
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public String getEntId() {
		return entId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_ORG_INFO.ENT_ID
	 * @param entId  the value for TB_ORG_INFO.ENT_ID
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public void setEntId(String entId) {
		this.entId = entId == null ? null : entId.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_ORG_INFO.CORP_CODE
	 * @return  the value of TB_ORG_INFO.CORP_CODE
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public String getCorpCode() {
		return corpCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_ORG_INFO.CORP_CODE
	 * @param corpCode  the value for TB_ORG_INFO.CORP_CODE
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public void setCorpCode(String corpCode) {
		this.corpCode = corpCode == null ? null : corpCode.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_ORG_INFO.CORP_BUSINESSNO
	 * @return  the value of TB_ORG_INFO.CORP_BUSINESSNO
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public String getCorpBusinessno() {
		return corpBusinessno;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_ORG_INFO.CORP_BUSINESSNO
	 * @param corpBusinessno  the value for TB_ORG_INFO.CORP_BUSINESSNO
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public void setCorpBusinessno(String corpBusinessno) {
		this.corpBusinessno = corpBusinessno == null ? null : corpBusinessno.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_ORG_INFO.SPECIAL_ID
	 * @return  the value of TB_ORG_INFO.SPECIAL_ID
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public String getSpecialId() {
		return specialId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_ORG_INFO.SPECIAL_ID
	 * @param specialId  the value for TB_ORG_INFO.SPECIAL_ID
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public void setSpecialId(String specialId) {
		this.specialId = specialId == null ? null : specialId.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_ORG_INFO.BUSINESS_SCOPE
	 * @return  the value of TB_ORG_INFO.BUSINESS_SCOPE
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public String getBusinessScope() {
		return businessScope;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_ORG_INFO.BUSINESS_SCOPE
	 * @param businessScope  the value for TB_ORG_INFO.BUSINESS_SCOPE
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public void setBusinessScope(String businessScope) {
		this.businessScope = businessScope == null ? null : businessScope.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_ORG_INFO.CERTIFICATE_OFFICE
	 * @return  the value of TB_ORG_INFO.CERTIFICATE_OFFICE
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public String getCertificateOffice() {
		return certificateOffice;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_ORG_INFO.CERTIFICATE_OFFICE
	 * @param certificateOffice  the value for TB_ORG_INFO.CERTIFICATE_OFFICE
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public void setCertificateOffice(String certificateOffice) {
		this.certificateOffice = certificateOffice == null ? null : certificateOffice.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_ORG_INFO.LICENCE_NO
	 * @return  the value of TB_ORG_INFO.LICENCE_NO
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public String getLicenceNo() {
		return licenceNo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_ORG_INFO.LICENCE_NO
	 * @param licenceNo  the value for TB_ORG_INFO.LICENCE_NO
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public void setLicenceNo(String licenceNo) {
		this.licenceNo = licenceNo == null ? null : licenceNo.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_ORG_INFO.CORP_QUALE
	 * @return  the value of TB_ORG_INFO.CORP_QUALE
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public String getCorpQuale() {
		return corpQuale;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_ORG_INFO.CORP_QUALE
	 * @param corpQuale  the value for TB_ORG_INFO.CORP_QUALE
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public void setCorpQuale(String corpQuale) {
		this.corpQuale = corpQuale == null ? null : corpQuale.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_ORG_INFO.CORP_BOSS
	 * @return  the value of TB_ORG_INFO.CORP_BOSS
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public BigDecimal getCorpBoss() {
		return corpBoss;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_ORG_INFO.CORP_BOSS
	 * @param corpBoss  the value for TB_ORG_INFO.CORP_BOSS
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public void setCorpBoss(BigDecimal corpBoss) {
		this.corpBoss = corpBoss;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_ORG_INFO.CORP_PAYSTATE
	 * @return  the value of TB_ORG_INFO.CORP_PAYSTATE
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public Short getCorpPaystate() {
		return corpPaystate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_ORG_INFO.CORP_PAYSTATE
	 * @param corpPaystate  the value for TB_ORG_INFO.CORP_PAYSTATE
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public void setCorpPaystate(Short corpPaystate) {
		this.corpPaystate = corpPaystate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_ORG_INFO.CORP_PAYTYPE
	 * @return  the value of TB_ORG_INFO.CORP_PAYTYPE
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public Short getCorpPaytype() {
		return corpPaytype;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_ORG_INFO.CORP_PAYTYPE
	 * @param corpPaytype  the value for TB_ORG_INFO.CORP_PAYTYPE
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public void setCorpPaytype(Short corpPaytype) {
		this.corpPaytype = corpPaytype;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_ORG_INFO.CORP_ECONOMYTYPE
	 * @return  the value of TB_ORG_INFO.CORP_ECONOMYTYPE
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public String getCorpEconomytype() {
		return corpEconomytype;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_ORG_INFO.CORP_ECONOMYTYPE
	 * @param corpEconomytype  the value for TB_ORG_INFO.CORP_ECONOMYTYPE
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public void setCorpEconomytype(String corpEconomytype) {
		this.corpEconomytype = corpEconomytype == null ? null : corpEconomytype.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_ORG_INFO.ORG_ADDRESS
	 * @return  the value of TB_ORG_INFO.ORG_ADDRESS
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public String getOrgAddress() {
		return orgAddress;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_ORG_INFO.ORG_ADDRESS
	 * @param orgAddress  the value for TB_ORG_INFO.ORG_ADDRESS
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public void setOrgAddress(String orgAddress) {
		this.orgAddress = orgAddress == null ? null : orgAddress.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_ORG_INFO.ORG_CZIP
	 * @return  the value of TB_ORG_INFO.ORG_CZIP
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public String getOrgCzip() {
		return orgCzip;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_ORG_INFO.ORG_CZIP
	 * @param orgCzip  the value for TB_ORG_INFO.ORG_CZIP
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public void setOrgCzip(String orgCzip) {
		this.orgCzip = orgCzip == null ? null : orgCzip.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_ORG_INFO.ORG_CFAX
	 * @return  the value of TB_ORG_INFO.ORG_CFAX
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public String getOrgCfax() {
		return orgCfax;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_ORG_INFO.ORG_CFAX
	 * @param orgCfax  the value for TB_ORG_INFO.ORG_CFAX
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public void setOrgCfax(String orgCfax) {
		this.orgCfax = orgCfax == null ? null : orgCfax.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_ORG_INFO.URL
	 * @return  the value of TB_ORG_INFO.URL
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_ORG_INFO.URL
	 * @param url  the value for TB_ORG_INFO.URL
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public void setUrl(String url) {
		this.url = url == null ? null : url.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_ORG_INFO.ORG_CMAIL
	 * @return  the value of TB_ORG_INFO.ORG_CMAIL
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public String getOrgCmail() {
		return orgCmail;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_ORG_INFO.ORG_CMAIL
	 * @param orgCmail  the value for TB_ORG_INFO.ORG_CMAIL
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public void setOrgCmail(String orgCmail) {
		this.orgCmail = orgCmail == null ? null : orgCmail.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_ORG_INFO.ORG_CNAME
	 * @return  the value of TB_ORG_INFO.ORG_CNAME
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public String getOrgCname() {
		return orgCname;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_ORG_INFO.ORG_CNAME
	 * @param orgCname  the value for TB_ORG_INFO.ORG_CNAME
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public void setOrgCname(String orgCname) {
		this.orgCname = orgCname == null ? null : orgCname.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_ORG_INFO.ORG_CNO
	 * @return  the value of TB_ORG_INFO.ORG_CNO
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public String getOrgCno() {
		return orgCno;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_ORG_INFO.ORG_CNO
	 * @param orgCno  the value for TB_ORG_INFO.ORG_CNO
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public void setOrgCno(String orgCno) {
		this.orgCno = orgCno == null ? null : orgCno.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_ORG_INFO.CREATE_UTC
	 * @return  the value of TB_ORG_INFO.CREATE_UTC
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public Long getCreateUtc() {
		return createUtc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_ORG_INFO.CREATE_UTC
	 * @param createUtc  the value for TB_ORG_INFO.CREATE_UTC
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public void setCreateUtc(Long createUtc) {
		this.createUtc = createUtc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_ORG_INFO.ORG_LOGO
	 * @return  the value of TB_ORG_INFO.ORG_LOGO
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public String getOrgLogo() {
		return orgLogo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_ORG_INFO.ORG_LOGO
	 * @param orgLogo  the value for TB_ORG_INFO.ORG_LOGO
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public void setOrgLogo(String orgLogo) {
		this.orgLogo = orgLogo == null ? null : orgLogo.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_ORG_INFO.ORG_MEM
	 * @return  the value of TB_ORG_INFO.ORG_MEM
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public String getOrgMem() {
		return orgMem;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_ORG_INFO.ORG_MEM
	 * @param orgMem  the value for TB_ORG_INFO.ORG_MEM
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public void setOrgMem(String orgMem) {
		this.orgMem = orgMem == null ? null : orgMem.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_ORG_INFO.ORG_CPHONE
	 * @return  the value of TB_ORG_INFO.ORG_CPHONE
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public String getOrgCphone() {
		return orgCphone;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_ORG_INFO.ORG_CPHONE
	 * @param orgCphone  the value for TB_ORG_INFO.ORG_CPHONE
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public void setOrgCphone(String orgCphone) {
		this.orgCphone = orgCphone == null ? null : orgCphone.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_ORG_INFO.ORG_SHORTNAME
	 * @return  the value of TB_ORG_INFO.ORG_SHORTNAME
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public String getOrgShortname() {
		return orgShortname;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_ORG_INFO.ORG_SHORTNAME
	 * @param orgShortname  the value for TB_ORG_INFO.ORG_SHORTNAME
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public void setOrgShortname(String orgShortname) {
		this.orgShortname = orgShortname == null ? null : orgShortname.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_ORG_INFO.CORP_COUNTRY
	 * @return  the value of TB_ORG_INFO.CORP_COUNTRY
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public String getCorpCountry() {
		return corpCountry;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_ORG_INFO.CORP_COUNTRY
	 * @param corpCountry  the value for TB_ORG_INFO.CORP_COUNTRY
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public void setCorpCountry(String corpCountry) {
		this.corpCountry = corpCountry == null ? null : corpCountry.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_ORG_INFO.CORP_PROVINCE
	 * @return  the value of TB_ORG_INFO.CORP_PROVINCE
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public String getCorpProvince() {
		return corpProvince;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_ORG_INFO.CORP_PROVINCE
	 * @param corpProvince  the value for TB_ORG_INFO.CORP_PROVINCE
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public void setCorpProvince(String corpProvince) {
		this.corpProvince = corpProvince == null ? null : corpProvince.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_ORG_INFO.CORP_CITY
	 * @return  the value of TB_ORG_INFO.CORP_CITY
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public String getCorpCity() {
		return corpCity;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_ORG_INFO.CORP_CITY
	 * @param corpCity  the value for TB_ORG_INFO.CORP_CITY
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public void setCorpCity(String corpCity) {
		this.corpCity = corpCity == null ? null : corpCity.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_ORG_INFO.LICENCE_WORD
	 * @return  the value of TB_ORG_INFO.LICENCE_WORD
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public String getLicenceWord() {
		return licenceWord;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_ORG_INFO.LICENCE_WORD
	 * @param licenceWord  the value for TB_ORG_INFO.LICENCE_WORD
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public void setLicenceWord(String licenceWord) {
		this.licenceWord = licenceWord == null ? null : licenceWord.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_ORG_INFO.ISDETEAM
	 * @return  the value of TB_ORG_INFO.ISDETEAM
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public String getIsdeteam() {
		return isdeteam;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_ORG_INFO.ISDETEAM
	 * @param isdeteam  the value for TB_ORG_INFO.ISDETEAM
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public void setIsdeteam(String isdeteam) {
		this.isdeteam = isdeteam == null ? null : isdeteam.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_ORG_INFO.CORP_LEVEL
	 * @return  the value of TB_ORG_INFO.CORP_LEVEL
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public String getCorpLevel() {
		return corpLevel;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_ORG_INFO.CORP_LEVEL
	 * @param corpLevel  the value for TB_ORG_INFO.CORP_LEVEL
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public void setCorpLevel(String corpLevel) {
		this.corpLevel = corpLevel == null ? null : corpLevel.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_ORG_INFO.BUSINESS_LICENSE
	 * @return  the value of TB_ORG_INFO.BUSINESS_LICENSE
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public String getBusinessLicense() {
		return businessLicense;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_ORG_INFO.BUSINESS_LICENSE
	 * @param businessLicense  the value for TB_ORG_INFO.BUSINESS_LICENSE
	 * @abatorgenerated  Mon Mar 24 16:46:50 CST 2014
	 */
	public void setBusinessLicense(String businessLicense) {
		this.businessLicense = businessLicense == null ? null : businessLicense.trim();
	}

	public Long getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Long updateTime) {
		this.updateTime = updateTime;
	}
	
}