 ############################################################
## makefile of libunisql.a
############################################################
.SUFFIXES: .cpp

SOURCES  = rc4coder.cpp intercoder.cpp
#SOURCES = testmain.cpp
PROGRAM  = 
CLIB     = libintercoder.a

SPECIAL_MACRO_FLAGS = -DRELEASE
SPECIAL_CCFLAGS   = 
SPECIAL_INCL_PATH = 
SPECIAL_LIB_PATH  = 

SPECIAL_LIBS = -lutils -llog -lthshare -lsocketex -lnetbaseex

include ${MTRANS_PRJ_HOME}/makefile.include


