############################################################
## makefile of libunisql.a
############################################################
.SUFFIXES: .cpp

SOURCES  = ../share/was/7ECoder.cpp bench.cpp vechilemgr.cpp systemenv.cpp main.cpp Logistics.cpp
#SOURCES = testmain.cpp
PROGRAM  = simv4
CLIB     = 

SPECIAL_MACRO_FLAGS = -DRELEASE
SPECIAL_CCFLAGS = 
SPECIAL_INCL_PATH = -I../share/was
SPECIAL_LIB_PATH = 

SPECIAL_LIBS = -lctfobase

include ${MTRANS_PRJ_HOME}/makefile.include


